USE [FMS]
GO

/****** Object:  View [dbo].[V002_NCR_J]    Script Date: 2019/01/30 11:09:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO













ALTER VIEW [dbo].[V002_NCR_J]
AS
SELECT 
 D003.HOKOKU_NO				--報告書No
,D003.BUMON_KB				--部門区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '部門区分' AND ITEM_VALUE=D003.BUMON_KB),'') AS BUMON_NAME	--部門名
,D003.CLOSE_FG				--クローズフラグ
,D003.KISYU_ID				--機種ID
--,isnull((SELECT KISYU FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = D003.KISYU_ID),'')		AS KISYU		--機種
,isnull((SELECT KISYU_NAME FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = D003.KISYU_ID),'')	AS KISYU_NAME	--機種名
,D003.SYANAI_CD				--社内コード
,D003.BUHIN_BANGO			--部品番号
,D003.BUHIN_NAME			--部品名称
,D003.GOKI					--号機
,D003.SURYO					--数量
,D003.SAIHATU				--再発
,D003.FUTEKIGO_JYOTAI_KB	--不適合状態区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合状態区分' AND ITEM_VALUE=D003.FUTEKIGO_JYOTAI_KB),'')	AS FUTEKIGO_JYOTAI_NAME	--不適合状態区分名
,D003.FUTEKIGO_NAIYO		--不適合状態内容
,D003.FUTEKIGO_KB			--不適合区分
,dbo.SC05_GET_FUTEKIGO_KB_DISP(D003.BUMON_KB,D003.FUTEKIGO_KB)  AS FUTEKIGO_NAME
--,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合区分' AND ITEM_VALUE=D003.FUTEKIGO_KB),'') AS FUTEKIGO_NAME	--不適合区分名
,D003.FUTEKIGO_S_KB			--不適合詳細区分
,dbo.SC04_GET_FUTEKIGO_S_KB_DISP(D003.BUMON_KB,D003.FUTEKIGO_KB,D003.FUTEKIGO_S_KB) AS FUTEKIGO_S_NAME	
/*
,CASE D003.FUTEKIGO_KB
 WHEN '0'	--外観
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合外観区分' AND ITEM_VALUE=D003.FUTEKIGO_S_KB),'')		
 WHEN '1'	--寸法
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合寸法区分' AND ITEM_VALUE=D003.FUTEKIGO_S_KB),'')		
 WHEN '2'	--形状
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合形状区分' AND ITEM_VALUE=D003.FUTEKIGO_S_KB),'')		
 WHEN '3'	--機能・性能
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合機能性能区分' AND ITEM_VALUE=D003.FUTEKIGO_S_KB),'')	
 WHEN '4'	--その他
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合その他区分' AND ITEM_VALUE=D003.FUTEKIGO_S_KB)	,'')
 ELSE '該当不適合区分なし' 
 END AS FUTEKIGO_S_NAME		--不適合詳細区分名
 */
,D003.ZUMEN_KIKAKU				--図面規格
,D003.YOKYU_NAIYO				--要求内容
,D003.KANSATU_KEKKA				--観察結果
,D003.ZESEI_SYOCHI_YOHI_KB		--是正処置要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=D003.ZESEI_SYOCHI_YOHI_KB),'')	 AS ZESEI_SYOCHI_YOHI_NAME				--不適合状態区分名
,D003.ZESEI_NASI_RIYU			--是正処置無理由
,D003.JIZEN_SINSA_HANTEI_KB		--事前審査判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '事前審査判定区分' AND ITEM_VALUE=D003.JIZEN_SINSA_HANTEI_KB),'') AS JIZEN_SINSA_HANTEI_NAME		--事前審査判定区分名
,D003.JIZEN_SINSA_SYAIN_ID		--事前審査社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.JIZEN_SINSA_SYAIN_ID)),'') AS JIZEN_SINSA_SYAIN_NAME
,D003.JIZEN_SINSA_YMD			--事前審査日
,D003.SAISIN_KAKUNIN_SYAIN_ID	--再審委員確認社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.SAISIN_KAKUNIN_SYAIN_ID)),'') AS SAISIN_KAKUNIN_SYAIN_NAME
,D003.SAISIN_KAKUNIN_YMD		--再審委員確認日
,D003.SAISIN_IINKAI_HANTEI_KB	--再審委員会判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '再審委員会判定区分' AND ITEM_VALUE=D003.SAISIN_IINKAI_HANTEI_KB),'') AS SAISIN_IINKAI_HANTEI_NAME	--再審委員会判定区分名
,D003.SAISIN_GIJYUTU_SYAIN_ID	--再審委員技術社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.SAISIN_GIJYUTU_SYAIN_ID)),'') AS SAISIN_GIJYUTU_SYAIN_NAME
,D003.SAISIN_GIJYUTU_YMD		--再審委員技術確認日
,D003.SAISIN_HINSYO_SYAIN_ID	--再審委員品証社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.SAISIN_HINSYO_SYAIN_ID)),'') AS SAISIN_HINSYO_SYAIN_NAME
,D003.SAISIN_HINSYO_YMD			--再審委員品証確認日
,D003.SAISIN_IINKAI_SIRYO_NO	--再審委員会資料No
,D003.ITAG_NO					--ITAGNo
,D003.KOKYAKU_SAISIN_TANTO_ID	--顧客再審申請担当ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.KOKYAKU_SAISIN_TANTO_ID)),'') AS KOKYAKU_SAISIN_TANTO_NAME
,D003.KOKYAKU_SAISIN_YMD		--顧客再審申請日
,D003.KOKYAKU_SAISIN_FILEPATH1		--顧客再審申請資料1
,D003.KOKYAKU_SAISIN_FILEPATH2		--顧客再審申請資料2
,D003.KOKYAKU_HANTEI_SIJI_KB	--顧客判定指示区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '顧客判定指示区分' AND ITEM_VALUE=D003.KOKYAKU_HANTEI_SIJI_KB),'') AS KOKYAKU_HANTEI_SIJI_NAME		--顧客判定指示区分名
,D003.KOKYAKU_HANTEI_SIJI_YMD	--顧客判定指示日
,D003.KOKYAKU_SAISYU_HANTEI_KB	--顧客最終判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '顧客最終判定区分' AND ITEM_VALUE=D003.KOKYAKU_SAISYU_HANTEI_KB),'') AS KOKYAKU_SAISYU_HANTEI_NAME		--顧客最終判定区分名
,D003.KOKYAKU_SAISYU_HANTEI_YMD	--顧客最終判定日
,D003.SAIKAKO_SIJI_FG			--再加工指示フラグ
,D003.HAIKYAKU_YMD				--廃却年月日
,D003.HAIKYAKU_KB				--廃却方法区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '廃却方法区分' AND ITEM_VALUE=D003.HAIKYAKU_KB),'') AS HAIKYAKU_KB_NAME							--顧客最終判定区分名
,D003.HAIKYAKU_HOUHOU			--廃却方法内容
,D003.HAIKYAKU_TANTO_ID			--廃却実施者ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.HAIKYAKU_TANTO_ID)),'') AS HAIKYAKU_TANTO_NAME
,D003.SAIKAKO_SIJI_NO			--再加工指示文書No
,D003.SAIKAKO_SAGYO_KAN_YMD		--再加工作業完了日
,D003.SAIKAKO_KENSA_YMD			--再加工検査年月日
,D003.KENSA_KEKKA_KB			--検査結果区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '検査結果区分' AND ITEM_VALUE=D003.KENSA_KEKKA_KB),'') AS KENSA_KEKKA_NAME						--検査結果区分名
,D003.SEIGI_TANTO_ID			--生技社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.SEIGI_TANTO_ID)),'') AS SEIGI_TANTO_NAME		--生技社員名
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 81),'') AS SEIGI_KAKUNIN_YMD	--生技確認年月日
,D003.SEIZO_TANTO_ID			--製造社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.SEIZO_TANTO_ID)),'') AS SEIZO_TANTO_NAME		--製造社員名
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 82),'') AS SEIZO_KAKUNIN_YMD	--製造確認年月日
,D003.KENSA_TANTO_ID			--検査社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.KENSA_TANTO_ID)),'') AS KENSA_TANTO_NAME		--検査社員名
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 83),'') AS KENSA_KAKUNIN_YMD	--検査確認年月日
,D003.HENKYAKU_YMD				--返却年月日
,D003.HENKYAKU_SAKI				--返却先
,D003.HENKYAKU_TANTO_ID			--返却実施者ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.HENKYAKU_TANTO_ID)),'') AS HENKYAKU_TANTO_NAME	--返却実施者名
,D003.HENKYAKU_BIKO				--返却実施備考
,D003.TENYO_KISYU_ID			--転用先機種ID
--,isnull((SELECT KISYU FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = D003.TENYO_KISYU_ID),'')		AS TENYO_KISYU		--転用先機種
,isnull((SELECT KISYU_NAME FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = D003.TENYO_KISYU_ID),'')	AS TENYO_KISYU_NAME	--転用先機種名
,D003.TENYO_BUHIN_BANGO			--転用先部品番号
,D003.TENYO_GOKI				--転用先号機
,D003.TENYO_LOT					--転用先LOT
,D003.TENYO_YMD					--転用年月日
,isnull((SELECT UPD_SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 90),'') AS SYONIN_NAME90	--NCR処置実施確認(90) 管理T
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN =90),'') AS SYONIN_YMD90	--NCR処置実施確認(90) 管理T年月日
,isnull((SELECT UPD_SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 100),'') AS SYONIN_NAME100	--NCR処置実施決裁(100) 製造課長
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN =100),'') AS SYONIN_YMD100		--NCR処置実施決裁(100) 製造課長
,isnull((SELECT UPD_SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 110),'') AS SYONIN_NAME110	--NCRabced処置担当(110)
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN =110),'') AS SYONIN_YMD110		--NCRabced処置担当(110)
,isnull((SELECT UPD_SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 120),'') AS SYONIN_NAME120	--NCRabced処置確認(120)
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN =120),'') AS SYONIN_YMD120		--NCRabced処置確認(120)
,D003.SYOCHI_KEKKA_A			--処置結果a
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=D003.SYOCHI_KEKKA_A),'') AS SYOCHI_KEKKA_A_NAME		--処置結果a名
,D003.SYOCHI_KEKKA_B			--処置結果b
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=D003.SYOCHI_KEKKA_B),'') AS SYOCHI_KEKKA_B_NAME		--処置結果b名
,D003.SYOCHI_KEKKA_C			--処置結果c
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=D003.SYOCHI_KEKKA_C),'') AS SYOCHI_KEKKA_C_NAME		--処置結果c名
,D003.SYOCHI_D_UMU_KB			--処置d有無区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '有無区分' AND ITEM_VALUE=D003.SYOCHI_D_UMU_KB),'') AS SYOCHI_D_UMU_NAME			--処置d有無区分名
,D003.SYOCHI_D_YOHI_KB			--処置d要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=D003.SYOCHI_D_YOHI_KB),'') AS SYOCHI_D_YOHI_NAME		--処置d要否区分名
,D003.SYOCHI_D_SYOCHI_KIROKU	--処置d処置記録
,D003.SYOCHI_E_UMU_KB			--処置e有無区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '有無区分' AND ITEM_VALUE=D003.SYOCHI_E_UMU_KB),'') AS SYOCHI_E_UMU_NAME			--処置e有無区分名
,D003.SYOCHI_E_YOHI_KB			--処置e要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=D003.SYOCHI_E_YOHI_KB),'') AS SYOCHI_E_YOHI_NAME		--処置e要否区分名
,D003.SYOCHI_E_SYOCHI_KIROKU	--処置e処置記録
,D003.FILE_PATH					--ファイルパス
,D003.G_FILE_PATH1				--画像ファイルパス1
,D003.G_FILE_PATH2				--画像ファイルパス2
,D003.ADD_YMDHNS				--追加日時
,D003.ADD_SYAIN_ID				--追加社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.ADD_SYAIN_ID)),'') AS ADD_SYAIN_NAME	--追加社員名
,D003.[UPD_YMDHNS]　　			--更新日時
,D003.[UPD_SYAIN_ID]			--更新社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.UPD_SYAIN_ID)),'') AS UPD_SYAIN_NAME	--更新社員名
,D003.[DEL_YMDHNS]				--削除日時
,D003.[DEL_SYAIN_ID]			--削除社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.DEL_SYAIN_ID)),'') AS DEL_SYAIN_NAME	--削除社員名
, (CASE RTRIM(D003.DEL_YMDHNS) WHEN '' THEN '0' ELSE '1' END) AS DEL_FLG
,isnull(D005.KONPON_YOIN_KB1,'') AS KONPON_YOIN_KB1	 	 	--根本要因区分1
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '根本要因区分' AND ITEM_VALUE=D005.KONPON_YOIN_KB1),'') AS KONPON_YOIN_NAME1		--根本要因区分名1
,isnull(D005.KONPON_YOIN_KB2,'') AS KONPON_YOIN_KB2			--根本要因区分2
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '根本要因区分' AND ITEM_VALUE=D005.KONPON_YOIN_KB2),'') AS KONPON_YOIN_NAME2		--根本要因区分名2
,isnull(D005.KISEKI_KOTEI_KB,'') AS KISEKI_KOTEI_KB			--帰責工程区分
,'' AS KISEKI_KOTEI_NAME		--帰責工程区分名
--,isnull((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
--		 WHERE 
--		     SYONIN_HOKOKUSYO_ID = 1
--		 AND HOKOKU_NO	= D003.HOKOKU_NO
--		 AND SYONIN_JUN = 20),'') AS HASSEI_KOTEI_GL_NAME	--発生工程GL名
,D003.HASSEI_KOTEI_GL_SYAIN_ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D003.HASSEI_KOTEI_GL_SYAIN_ID)),'') AS HASSEI_KOTEI_GL_SYAIN_NAME
,isnull((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE 
		     SYONIN_HOKOKUSYO_ID = 1
		 AND HOKOKU_NO	= D003.HOKOKU_NO
		 AND SYONIN_JUN = 20),'') AS HASSEI_KOTEI_GL_YMD	--発生工程GL年月日
,D003.HASSEI_YMD
,D003.SAI_FUTEKIGO_KISO_TANTO_ID
FROM
D003_NCR_J AS D003 LEFT OUTER JOIN
D005_CAR_J AS D005 ON 
D003.HOKOKU_NO = D005.HOKOKU_NO
		  
GO


