USE [FMS]
GO

/****** Object:  View [dbo].[V003_SYONIN_J_KANRI]    Script Date: 2018/05/22 18:30:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[V003_SYONIN_J_KANRI]
AS
SELECT 
 D004.SYONIN_HOKOKUSYO_ID	--承認報告書ID
,D004.HOKOKU_NO				--報告書No
,D004.SYONIN_JUN			--承認順
,isnull((SELECT SYONIN_NAIYO FROM M014_SYONIN_ROUT 
  WHERE 
      SYONIN_HOKOKUSYO_ID = D004.SYONIN_HOKOKUSYO_ID
  AND SYONIN_JUN		  = D004.SYONIN_JUN),'') AS SYONIN_NAIYO
,D004.SYAIN_ID				--社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D004.ADD_SYAIN_ID)),'') AS SYAIN_NAME	--追加社員名
,D004.SYONIN_YMDHNS			--承認日時
,D004.SYONIN_HANTEI_KB		--承認判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '承認判定区分' AND ITEM_VALUE=D004.SYONIN_HANTEI_KB),'')	 AS SYONIN_HANTEI_NAME	--承認判定区分名
,D004.SASIMODOSI_FG			--差戻フラグ
,D004.RIYU					--理由
,D004.COMMENT				--コメント
,D004.MAIL_SEND_FG			--メール送信フラグ
,D004.ADD_YMDHNS				--追加日時
,D004.ADD_SYAIN_ID				--追加社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D004.ADD_SYAIN_ID)),'') AS ADD_SYAIN_NAME	--追加社員名
,D004.[UPD_YMDHNS]　　			--更新日時
,D004.[UPD_SYAIN_ID]			--更新社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D004.UPD_SYAIN_ID)),'') AS UPD_SYAIN_NAME	--更新社員名
FROM
	D004_SYONIN_J_KANRI AS D004
		  
GO


