 ALTER VIEW [dbo].[V004_HOKOKU_SOUSA]
 AS
SELECT 
 SYONIN_HOKOKUSYO_ID	--承認報告書ID
,isnull((SELECT SYONIN_HOKOKUSYO_NAME FROM M013_SYONIN_HOKOKU WHERE SYONIN_HOKOKUSYO_ID = R001.SYONIN_HOKOKUSYO_ID),'') AS SYONIN_HOKOKUSYO_NAME 
,isnull((SELECT SYONIN_HOKOKUSYO_R_NAME FROM M013_SYONIN_HOKOKU WHERE SYONIN_HOKOKUSYO_ID = R001.SYONIN_HOKOKUSYO_ID),'') AS SYONIN_HOKOKUSYO_R_NAME
,HOKOKU_NO				--報告書No
,ADD_YMDHNS				--追加日時
,SYONIN_JUN				--承認順
 ,isnull((SELECT SYONIN_NAIYO FROM M014_SYONIN_ROUT 
   WHERE 
       SYONIN_HOKOKUSYO_ID = R001.SYONIN_HOKOKUSYO_ID
   AND SYONIN_JUN		  = R001.SYONIN_JUN),'') AS SYONIN_NAIYO
 ,SOUSA_KB				--操作区分
 ,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '操作区分' AND ITEM_VALUE=R001.SOUSA_KB),'') AS SOUSA_NAME		--操作区分名
 ,SYAIN_ID				--社員ID
 ,isnull((SELECT SYAIN_NO FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R001.SYAIN_ID)),'') AS SYAIN_NO
 ,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R001.SYAIN_ID)),'') AS SYAIN_NAME
 ,SYONIN_HANTEI_KB		--承認判定区分
 ,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '承認判定区分' AND ITEM_VALUE=R001.SYONIN_HANTEI_KB),'') AS SYONIN_HANTEI_NAME		--承認判定区分名
 ,RIYU					--理由
 ,ADD_YMDHNS AS SASIMODOSI_YMDHNS
 ,dbo.[SC03_HENKOU_FIELD_COUNT](ADD_YMDHNS,SYONIN_HOKOKUSYO_ID,HOKOKU_NO) AS HENKOU_KENSU
,isnull((SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI D004 
					WHERE D004.SYONIN_HOKOKUSYO_ID = R001.SYONIN_HOKOKUSYO_ID
									AND D004.HOKOKU_NO = R001.HOKOKU_NO
									AND D004.SYONIN_JUN = R001.SYONIN_JUN),0) AS MODOSI_SAKI_SYAIN_ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = isnull((SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI D004 
					WHERE D004.SYONIN_HOKOKUSYO_ID = R001.SYONIN_HOKOKUSYO_ID
									AND D004.HOKOKU_NO = R001.HOKOKU_NO
									AND D004.SYONIN_JUN = R001.SYONIN_JUN),0))),'') AS MODOSI_SAKI_SYAIN_NAME
FROM
	R001_HOKOKU_SOUSA AS R001