USE [FMS]
GO

/****** Object:  View [dbo].[V006_CAR_GENIN]    Script Date: 2018/05/11 9:30:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[V006_CAR_GENIN]
AS
SELECT 
 D006.HOKOKU_NO				--報告書No
,D006.RENBAN				--連番
,D006.GENIN_BUNSEKI_KB		--原因分析区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '原因分析区分' AND ITEM_VALUE=D006.GENIN_BUNSEKI_KB),'') AS SOUSA_NAME		--原因分析区分名
,D006.GENIN_BUNSEKI_S_KB	--原因分析詳細区分
,CASE D006.GENIN_BUNSEKI_KB
 WHEN '0'	--m-マネジメント
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_m区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '1'	--S-ソフトウェア
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_S区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '2'	--h-ハードウェア
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_H区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '3'	--e-作業環境
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_E区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '4'	--L1-本人
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_L1区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '5'	--L2-関係者・支援体制
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'm-SHELL_L2区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '11'	--材料
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '材料原因区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '12'	--設備・治具
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '設備治具原因区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 WHEN '13'	--方法
 	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '方法原因区分' AND ITEM_VALUE = D006.GENIN_BUNSEKI_S_KB),'')	 
 ELSE ' '
 END AS GENIN_BUNSEKI_NAME
,D006.DAIHYO_FG				--代表フラグ
,D006.ADD_SYAIN_ID			--追加社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = D006.ADD_SYAIN_ID)),'') AS ADD_SYAIN_NAME
,D006.ADD_YMDHNS			--追加日時
FROM
	D006_CAR_GENIN AS D006
		  
GO


