USE [FMS]
GO

/****** Object:  View [dbo].[V007_NCR_CAR_BUNSEKI]    Script Date: 2021/06/03 11:57:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW [dbo].[V007_NCR_CAR_BUNSEKI]
AS
SELECT
    HOKOKU_NO
  , SYONIN_JUN
  , SYONIN_NAIYO
  , SYONIN_HOKOKUSYO_ID
  , SYONIN_HOKOKUSYO_NAME
  , SYONIN_HOKOKUSYO_R_NAME
  , GEN_TANTO_ID
  , GEN_TANTO_NAME
  , SYONIN_YMDHNS
  , TAIRYU_NISSU
  , TOTAL_TAIRYU_NISSU
  , TAIRYU_FG
  , KISYU_ID
  , KISYU_NAME
  , BUHIN_BANGO
  , BUHIN_NAME
  , GOKI
  , SYANAI_CD
  , FUTEKIGO_KB
  , FUTEKIGO_NAME
  , FUTEKIGO_S_KB
  , FUTEKIGO_S_NAME
  , FUTEKIGO_JYOTAI_KB
  , FUTEKIGO_JYOTAI_NAME
  , JIZEN_SINSA_HANTEI_KB
  , JIZEN_SINSA_HANTEI_NAME
  , ZESEI_SYOCHI_YOHI_KB
  , ZESEI_SYOCHI_YOHI_NAME
  , SAISIN_IINKAI_HANTEI_KB
  , SAISIN_IINKAI_HANTEI_NAME
  , KENSA_KEKKA_KB
  , KENSA_KEKKA_NAME
  , KONPON_YOIN_KB1 KONPON_YOIN_KB
  , KONPON_YOIN_NAME1 KONPON_YOIN_NAME
  , KISEKI_KOTEI_KB
  , KISEKI_KOTEI_NAME
  , SYOCHI_YOTEI_YMD
  , KISO_YMD
  , KISO_TANTO_ID
  , KISO_TANTO_NAME
  , CLOSE_FG
  , SASIMOTO_SYONIN_JUN
  , SASIMOTO_SYONIN_NAIYO
  , RIYU
  , YOKYU_NAIYO
  , KANSATU_KEKKA
  , BUMON_KB
  , BUMON_NAME
  , KOKYAKU_HANTEI_SIJI_KB
  , KOKYAKU_HANTEI_SIJI_NAME
  , KOKYAKU_SAISYU_HANTEI_KB
  , KOKYAKU_SAISYU_HANTEI_NAME
  , DEL_YMDHNS
  , HASSEI_YMD
  , SURYO 
FROM
  V007_NCR_CAR
UNION
SELECT
    HOKOKU_NO
  , SYONIN_JUN
  , SYONIN_NAIYO
  , SYONIN_HOKOKUSYO_ID
  , SYONIN_HOKOKUSYO_NAME
  , SYONIN_HOKOKUSYO_R_NAME
  , GEN_TANTO_ID
  , GEN_TANTO_NAME
  , SYONIN_YMDHNS
  , TAIRYU_NISSU
  , TOTAL_TAIRYU_NISSU
  , TAIRYU_FG
  , KISYU_ID
  , KISYU_NAME
  , BUHIN_BANGO
  , BUHIN_NAME
  , GOKI
  , SYANAI_CD
  , FUTEKIGO_KB
  , FUTEKIGO_NAME
  , FUTEKIGO_S_KB
  , FUTEKIGO_S_NAME
  , FUTEKIGO_JYOTAI_KB
  , FUTEKIGO_JYOTAI_NAME
  , JIZEN_SINSA_HANTEI_KB
  , JIZEN_SINSA_HANTEI_NAME
  , ZESEI_SYOCHI_YOHI_KB
  , ZESEI_SYOCHI_YOHI_NAME
  , SAISIN_IINKAI_HANTEI_KB
  , SAISIN_IINKAI_HANTEI_NAME
  , KENSA_KEKKA_KB
  , KENSA_KEKKA_NAME
  , KONPON_YOIN_KB2 KONPON_YOIN_KB
  , KONPON_YOIN_NAME2 KONPON_YOIN_NAME
  , KISEKI_KOTEI_KB
  , KISEKI_KOTEI_NAME
  , SYOCHI_YOTEI_YMD
  , KISO_YMD
  , KISO_TANTO_ID
  , KISO_TANTO_NAME
  , CLOSE_FG
  , SASIMOTO_SYONIN_JUN
  , SASIMOTO_SYONIN_NAIYO
  , RIYU
  , YOKYU_NAIYO
  , KANSATU_KEKKA
  , BUMON_KB
  , BUMON_NAME
  , KOKYAKU_HANTEI_SIJI_KB
  , KOKYAKU_HANTEI_SIJI_NAME
  , KOKYAKU_SAISYU_HANTEI_KB
  , KOKYAKU_SAISYU_HANTEI_NAME
  , DEL_YMDHNS
  , HASSEI_YMD
  , SURYO 
FROM
  V007_NCR_CAR
where KONPON_YOIN_KB2 != '' 

GO


