USE [FMS]
GO

/****** Object:  View [dbo].[V008_NCR_R]    Script Date: 2019/01/30 11:12:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






USE [FMS_TEST]
GO

/****** Object:  View [dbo].[V008_NCR_R]    Script Date: 2022/02/09 11:43:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO










ALTER VIEW [dbo].[V008_NCR_R]
AS
SELECT 
 R003.SASIMODOSI_YMDHNS		--差戻日時
,R003.HOKOKU_NO				--報告書No
,R003.BUMON_KB				--部門区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '部門区分' AND ITEM_VALUE=R003.BUMON_KB),'') AS BUMON_NAME	--部門名
,R003.CLOSE_FG				--クローズフラグ
,R003.KISYU_ID				--機種ID
--,isnull((SELECT KISYU FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = R003.KISYU_ID),'')		AS KISYU		--機種
,isnull((SELECT KISYU_NAME FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = R003.KISYU_ID),'')	AS KISYU_NAME	--機種名
,R003.SYANAI_CD				--社内コード
,R003.BUHIN_BANGO			--部品番号
,R003.BUHIN_NAME			--部品名称
,R003.GOKI					--号機
,R003.SURYO					--数量
,R003.SAIHATU				--再発
,R003.FUTEKIGO_JYOTAI_KB	--不適合状態区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合状態区分' AND ITEM_VALUE=R003.FUTEKIGO_JYOTAI_KB),'')	AS FUTEKIGO_JYOTAI_NAME	--不適合状態区分名
,R003.FUTEKIGO_NAIYO		--不適合状態内容
,R003.FUTEKIGO_KB			--不適合区分
,dbo.SC05_GET_FUTEKIGO_KB_DISP(R003.BUMON_KB,R003.FUTEKIGO_KB)  AS FUTEKIGO_NAME
--,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合区分' AND ITEM_VALUE=R003.FUTEKIGO_KB),'') AS FUTEKIGO_NAME	--不適合区分名
,R003.FUTEKIGO_S_KB			--不適合詳細区分
,dbo.SC04_GET_FUTEKIGO_S_KB_DISP(R003.BUMON_KB,R003.FUTEKIGO_KB,R003.FUTEKIGO_S_KB) AS FUTEKIGO_S_NAME	
/*
,CASE R003.FUTEKIGO_KB
 WHEN '0'	--外観
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合外観区分' AND ITEM_VALUE=R003.FUTEKIGO_S_KB),'')		
 WHEN '1'	--寸法
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合寸法区分' AND ITEM_VALUE=R003.FUTEKIGO_S_KB),'')		
 WHEN '2'	--形状
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合形状区分' AND ITEM_VALUE=R003.FUTEKIGO_S_KB),'')		
 WHEN '3'	--機能・性能
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合機能性能区分' AND ITEM_VALUE=R003.FUTEKIGO_S_KB),'')	
 WHEN '4'	--その他
	THEN isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '不適合その他区分' AND ITEM_VALUE=R003.FUTEKIGO_S_KB)	,'')
 ELSE '該当不適合区分なし' 
 END AS FUTEKIGO_S_NAME		--不適合詳細区分名
 */
,R003.ZUMEN_KIKAKU				--図面規格
,R003.YOKYU_NAIYO				--要求内容
,R003.KANSATU_KEKKA				--観察結果
,R003.ZESEI_SYOCHI_YOHI_KB		--是正処置要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=R003.ZESEI_SYOCHI_YOHI_KB),'')	 AS ZESEI_SYOCHI_YOHI_NAME				--不適合状態区分名
,R003.ZESEI_NASI_RIYU			--是正処置無理由
,R003.JIZEN_SINSA_HANTEI_KB		--事前審査判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '事前審査判定区分' AND ITEM_VALUE=R003.JIZEN_SINSA_HANTEI_KB),'') AS JIZEN_SINSA_HANTEI_NAME		--事前審査判定区分名
,R003.JIZEN_SINSA_SYAIN_ID		--事前審査社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.JIZEN_SINSA_SYAIN_ID)),'') AS JIZEN_SINSA_SYAIN_NAME
,R003.JIZEN_SINSA_YMD			--事前審査日
,R003.SAISIN_KAKUNIN_SYAIN_ID	--再審委員確認社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.SAISIN_KAKUNIN_SYAIN_ID)),'') AS SAISIN_KAKUNIN_SYAIN_NAME
,R003.SAISIN_KAKUNIN_YMD		--再審委員確認日
,R003.SAISIN_IINKAI_HANTEI_KB	--再審委員会判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '再審委員会判定区分' AND ITEM_VALUE=R003.SAISIN_IINKAI_HANTEI_KB),'') AS SAISIN_IINKAI_HANTEI_NAME	--再審委員会判定区分名
,R003.SAISIN_GIJYUTU_SYAIN_ID	--再審委員技術社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.SAISIN_GIJYUTU_SYAIN_ID)),'') AS SAISIN_GIJYUTU_SYAIN_NAME
,R003.SAISIN_GIJYUTU_YMD		--再審委員技術確認日
,R003.SAISIN_HINSYO_SYAIN_ID	--再審委員品証社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.SAISIN_HINSYO_SYAIN_ID)),'') AS SAISIN_HINSYO_SYAIN_NAME
,R003.SAISIN_HINSYO_YMD			--再審委員品証確認日
,R003.SAISIN_IINKAI_SIRYO_NO	--再審委員会資料No
,R003.ITAG_NO					--ITAGNo
,R003.KOKYAKU_SAISIN_TANTO_ID	--顧客再審申請担当ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.KOKYAKU_SAISIN_TANTO_ID)),'') AS KOKYAKU_SAISIN_TANTO_NAME
,R003.KOKYAKU_SAISIN_YMD		--顧客再審申請日
,R003.KOKYAKU_SAISIN_FILEPATH1		--顧客再審申請資料1
,R003.KOKYAKU_SAISIN_FILEPATH2		--顧客再審申請資料2
,R003.KOKYAKU_HANTEI_SIJI_KB	--顧客判定指示区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '顧客判定指示区分' AND ITEM_VALUE=R003.KOKYAKU_HANTEI_SIJI_KB),'') AS KOKYAKU_HANTEI_SIJI_NAME		--顧客判定指示区分名
,R003.KOKYAKU_HANTEI_SIJI_YMD	--顧客判定指示日
,R003.KOKYAKU_SAISYU_HANTEI_KB	--顧客最終判定区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '顧客最終判定区分' AND ITEM_VALUE=R003.KOKYAKU_SAISYU_HANTEI_KB),'') AS KOKYAKU_SAISYU_HANTEI_NAME		--顧客最終判定区分名
,R003.KOKYAKU_SAISYU_HANTEI_YMD	--顧客最終判定日
,R003.SAIKAKO_SIJI_FG			--再加工指示フラグ
,R003.HAIKYAKU_YMD				--廃却年月日
,R003.HAIKYAKU_KB				--廃却方法区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '廃却方法区分' AND ITEM_VALUE=R003.HAIKYAKU_KB),'') AS HAIKYAKU_KB_NAME							--顧客最終判定区分名
,R003.HAIKYAKU_HOUHOU			--廃却方法内容
,R003.HAIKYAKU_TANTO_ID			--廃却実施者ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.HAIKYAKU_TANTO_ID)),'') AS HAIKYAKU_TANTO_NAME
,R003.SAIKAKO_SIJI_NO			--再加工指示文書No
,R003.SAIKAKO_SAGYO_KAN_YMD		--再加工作業完了日
,R003.SAIKAKO_KENSA_YMD			--再加工検査年月日
,R003.KENSA_KEKKA_KB			--検査結果区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '検査結果区分' AND ITEM_VALUE=R003.KENSA_KEKKA_KB),'') AS KENSA_KEKKA_NAME						--検査結果区分名
,R003.SEIGI_TANTO_ID			--生技社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.SEIGI_TANTO_ID)),'') AS SEIGI_TANTO_NAME		--生技社員名
,R003.SEIZO_TANTO_ID			--製造社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.SEIZO_TANTO_ID)),'') AS SEIZO_TANTO_NAME		--製造社員名
,R003.KENSA_TANTO_ID			--検査社員ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.KENSA_TANTO_ID)),'') AS KENSA_TANTO_NAME		--検査社員名
,R003.HENKYAKU_YMD				--返却年月日
,R003.HENKYAKU_SAKI				--返却先
,R003.HENKYAKU_TANTO_ID			--返却実施者ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.HENKYAKU_TANTO_ID)),'') AS HENKYAKU_TANTO_NAME	--検査社員名
,R003.HENKYAKU_BIKO				--返却実施備考
,R003.TENYO_KISYU_ID			--転用先機種ID
--,isnull((SELECT KISYU FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = R003.TENYO_KISYU_ID),'')		AS TENYO_KISYU		--転用先機種
,isnull((SELECT KISYU_NAME FROM M105_KISYU AS M105 WHERE M105.KISYU_ID = R003.TENYO_KISYU_ID),'')	AS TENYO_KISYU_NAME	--転用先機種名
,R003.TENYO_BUHIN_BANGO			--転用先部品番号
,R003.TENYO_GOKI				--転用先号機
,R003.TENYO_LOT					--転用先LOT
,R003.TENYO_YMD					--転用年月日
,R003.SYOCHI_KEKKA_A			--処置結果a
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=R003.SYOCHI_KEKKA_A),'') AS SYOCHI_KEKKA_A_NAME		--処置結果a名
,R003.SYOCHI_KEKKA_B			--処置結果b
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=R003.SYOCHI_KEKKA_B),'') AS SYOCHI_KEKKA_B_NAME		--処置結果b名
,R003.SYOCHI_KEKKA_C			--処置結果c
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '処置結果区分' AND ITEM_VALUE=R003.SYOCHI_KEKKA_C),'') AS SYOCHI_KEKKA_C_NAME		--処置結果c名
,R003.SYOCHI_D_UMU_KB			--処置d有無区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '有無区分' AND ITEM_VALUE=R003.SYOCHI_D_UMU_KB),'') AS SYOCHI_D_UMU_NAME			--処置d有無区分名
,R003.SYOCHI_D_YOHI_KB			--処置d要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=R003.SYOCHI_D_YOHI_KB),'') AS SYOCHI_D_YOHI_NAME		--処置d要否区分名
,R003.SYOCHI_D_SYOCHI_KIROKU	--処置d処置記録
,R003.SYOCHI_E_UMU_KB			--処置e有無区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '有無区分' AND ITEM_VALUE=R003.SYOCHI_E_UMU_KB),'') AS SYOCHI_E_UMU_NAME			--処置e有無区分名
,R003.SYOCHI_E_YOHI_KB			--処置e要否区分
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '要否区分' AND ITEM_VALUE=R003.SYOCHI_E_YOHI_KB),'') AS SYOCHI_E_YOHI_NAME		--処置e要否区分名
,R003.SYOCHI_E_SYOCHI_KIROKU	--処置e処置記録
,R003.FILE_PATH					--ファイルパス
,R003.G_FILE_PATH1				--画像ファイルパス1
,R003.G_FILE_PATH2				--画像ファイルパス2
,R003.HASSEI_KOTEI_GL_SYAIN_ID
,isnull((SELECT SIMEI FROM M004_SYAIN AS M04 WHERE(M04.SYAIN_ID = R003.HASSEI_KOTEI_GL_SYAIN_ID)),'') AS HASSEI_KOTEI_GL_SYAIN_NAME
,R003.SAI_FUTEKIGO_KISO_TANTO_ID
,R003.SAI_KAKO_NG_SURYO
,R003.SAI_KAKO_COMMENT
FROM
R003_NCR_SASIMODOSI AS R003 
		  
GO


