ALTER VIEW dbo.V015_ZESEI_ICHIRAN AS 
SELECT
    D013.HOKOKU_NO
	,isnull((SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
			 WHERE SYONIN_HOKOKUSYO_ID = 5 
			 AND HOKOKU_NO = D013.HOKOKU_NO 
			 AND SYONIN_HANTEI_KB = '0' ),999) AS SYONIN_JUN		--承認順
	,isnull((SELECT SYONIN_NAIYO FROM M014_SYONIN_ROUT
	  WHERE 
	  SYONIN_HOKOKUSYO_ID = 5
	  AND SYONIN_JUN = isnull((SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
							   WHERE SYONIN_HOKOKUSYO_ID = 5
							   AND HOKOKU_NO = D013.HOKOKU_NO 
							   AND SYONIN_HANTEI_KB = '0'),0)),(SELECT SYONIN_NAIYO fROM M014_SYONIN_ROUT WHERE SYONIN_HOKOKUSYO_ID= 1 AND SYONIN_JUN =999 )) AS SYONIN_NAIYO	--承認内容（ステージ）
	,5	AS SYONIN_HOKOKUSYO_ID		--承認報告書ID
	,(SELECT SYONIN_HOKOKUSYO_NAME		FROM M013_SYONIN_HOKOKU 
	  WHERE SYONIN_HOKOKUSYO_ID = 5)	AS SYONIN_HOKOKUSYO_NAME			--承認報告書名
	,(SELECT SYONIN_HOKOKUSYO_R_NAME	FROM M013_SYONIN_HOKOKU 
	  WHERE SYONIN_HOKOKUSYO_ID = 5) AS SYONIN_HOKOKUSYO_R_NAME				--承認報告書略名
	,isnull((SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI 
	  WHERE SYONIN_HOKOKUSYO_ID = 5 
	  AND HOKOKU_NO = D013.HOKOKU_NO 
	  AND SYONIN_JUN = (SELECT MIN(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
						WHERE SYONIN_HOKOKUSYO_ID = 5
						  AND HOKOKU_NO = D013.HOKOKU_NO 
						  AND SYONIN_HANTEI_KB = '0')),'') AS GEN_TANTO_ID			--承認担当者ID（現処置担当者ID）
	,isnull((SELECT SIMEI FROM M004_SYAIN
	  WHERE 
	  SYAIN_ID = (SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI 
				 WHERE SYONIN_HOKOKUSYO_ID = 5 
				  AND HOKOKU_NO = D013.HOKOKU_NO 
				  AND SYONIN_JUN = (SELECT MIN(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
									WHERE SYONIN_HOKOKUSYO_ID = 5
									AND HOKOKU_NO = D013.HOKOKU_NO 
									AND SYONIN_HANTEI_KB = '0'))),'')	AS GEN_TANTO_NAME	--承認担当者名
	,ISNULL((SELECT MAX(UPD_YMDHNS) FROM D004_SYONIN_J_KANRI
	  WHERE SYONIN_HOKOKUSYO_ID = 5
	   AND HOKOKU_NO = D013.HOKOKU_NO
		 AND SYONIN_HANTEI_KB = '1'),'') AS SYONIN_YMDHNS							--承認日時（処置実施日および前処置実施日）
		 
	,CASE CLOSE_FG 
	 WHEN '0' THEN
		dbo.SC02_GET_TAIRYU_NISSU('1'
							   ,(SELECT MAX(CASE WHEN UPD_YMDHNS='' THEN ADD_YMDHNS ELSE UPD_YMDHNS END) FROM D004_SYONIN_J_KANRI
								 WHERE SYONIN_HOKOKUSYO_ID = 5
								  AND HOKOKU_NO = D013.HOKOKU_NO
									AND SYONIN_HANTEI_KB = '0')
							   ,CONVERT(nvarchar,GETDATE(),112)
								 )
	ELSE '0'
	END		AS TAIRYU_NISSU									--滞留日数	
	,dbo.SC02_GET_TAIRYU_NISSU('1',SUBSTRING(D013.ADD_YMDHNS,1,8),CONVERT(nvarchar,GETDATE(),112)) TOTAL_TAIRYU_NISSU	--累計滞留日数
	,CASE CLOSE_FG 
	 WHEN '0' THEN
		CASE WHEN dbo.SC02_GET_TAIRYU_NISSU('1'
										,(SELECT MAX(CASE WHEN UPD_YMDHNS='' THEN ADD_YMDHNS ELSE UPD_YMDHNS END) FROM D004_SYONIN_J_KANRI
										  WHERE SYONIN_HOKOKUSYO_ID = 5
										  AND HOKOKU_NO = D013.HOKOKU_NO
														AND SYONIN_HANTEI_KB = '0')
										 ,CONVERT(nvarchar,GETDATE(),112)) >= (SELECT KEIKOKU_TAIRYU_NISSU FROM M014_SYONIN_ROUT 
																				WHERE SYONIN_HOKOKUSYO_ID = 5
																				AND SYONIN_JUN = (SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
																								  WHERE SYONIN_HOKOKUSYO_ID = 5
																									AND HOKOKU_NO = D013.HOKOKU_NO 
																									AND SYONIN_HANTEI_KB = '0')) THEN '1'
		 ELSE '0' END 
	 ELSE 0 END	 AS TAIRYU_FG		--滞留フラグ
  , D013.CLOSE_FG
  , D013.BUMON_KB
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '部門区分' AND ITEM_VALUE=D013.BUMON_KB),'') AS BUMON_NAME	----部門区分名
  , D013.BUSYO_ID
  , isnull((SELECT BUSYO_NAME FROM M002_BUSYO AS M002 WHERE M002.BUSYO_ID = D013.BUSYO_ID), '') AS BUSYO_NAME
  , D013.TANTO_ID 
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D013.TANTO_ID = M.SYAIN_ID)),'') AS TANTO_NAME
  , D013.INPUT_TYPE
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '是正処置区分' AND ITEM_VALUE=D013.INPUT_TYPE),'') AS INPUT_TYPE_DISP
  , D013.DOC_NO
  , D013.KAITOU_KIBOU_YMD
  , D013.KANSATU_HOUKOKU 
  , D013.ZESEI_RIYU 
  , D013.ZESEI_COMMENT
  , D013.KAITOU_YMD
  , D013.FUTEKIGO_TAISYOU
  , D013.CHOUSA_HANI
  , D013.FUTEKIGO_UMU
  , D013.EIKYOU_HANI
  , D013.OUKYU_SYOCHI
  , D013.OUKYU_SYOCHI_YOTEI_YMD
  , D013.JINTEKI_YOUIN_UMU
  , D013.HASSEI_GENIN
  , D013.ZESEI_SYOCHI
  , D013.ZESEI_SYOCHI_YOTEI_YMD
  , D013.ZESEI_SYOCHI_YMD
  , D013.OUKYU_SYOCHI_YMD
  , D013.OUKYU_SYOCHI_KEKKA
  , D013.ZESEI_SYOCHI_KEKKA
  , D013.ZESEI_SYOCHI_HANTEI
  , D013.ZESEI_SYOCHI_NG_DOC_NO
  , D013.FILE_PATH1
  , D013.FILE_PATH2
  , D013.FILE_PATH3
  , D013.FILE_PATH4
  , D013.FILE_PATH5
  , D013.COMMENT1
  , D013.COMMENT2
  , D013.COMMENT3
  , D013.COMMENT4
  , D013.COMMENT5
  , D013.ADD_YMDHNS
  , D013.ADD_SYAIN_ID
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D013.ADD_SYAIN_ID = M.SYAIN_ID)),'') AS ADD_TANTO_NAME
  , D013.DEL_YMDHNS
  , D013.DEL_SYAIN_ID
FROM
  D013_ZESEI_HASSEI_J D013

   
UNION ALL 
SELECT
    D014.HOKOKU_NO
		,isnull((SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
			 WHERE SYONIN_HOKOKUSYO_ID = 6 
			 AND HOKOKU_NO = D014.HOKOKU_NO 
			 AND SYONIN_HANTEI_KB = '0' ),999) AS SYONIN_JUN		--承認順
	,isnull((SELECT SYONIN_NAIYO FROM M014_SYONIN_ROUT
	  WHERE 
	  SYONIN_HOKOKUSYO_ID = 6
	  AND SYONIN_JUN = isnull((SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
							   WHERE SYONIN_HOKOKUSYO_ID = 6
							   AND HOKOKU_NO = D014.HOKOKU_NO 
							   AND SYONIN_HANTEI_KB = '0'),0)),(SELECT SYONIN_NAIYO fROM M014_SYONIN_ROUT WHERE SYONIN_HOKOKUSYO_ID= 1 AND SYONIN_JUN =999 )) AS SYONIN_NAIYO	--承認内容（ステージ）
	,6	AS SYONIN_HOKOKUSYO_ID		--承認報告書ID
	,(SELECT SYONIN_HOKOKUSYO_NAME		FROM M013_SYONIN_HOKOKU 
	  WHERE SYONIN_HOKOKUSYO_ID = 6)	AS SYONIN_HOKOKUSYO_NAME			--承認報告書名
	,(SELECT SYONIN_HOKOKUSYO_R_NAME	FROM M013_SYONIN_HOKOKU 
	  WHERE SYONIN_HOKOKUSYO_ID = 6) AS SYONIN_HOKOKUSYO_R_NAME				--承認報告書略名
	,isnull((SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI 
	  WHERE SYONIN_HOKOKUSYO_ID = 6 
	  AND HOKOKU_NO = D014.HOKOKU_NO 
	  AND SYONIN_JUN = (SELECT MIN(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
						WHERE SYONIN_HOKOKUSYO_ID = 6
						  AND HOKOKU_NO = D014.HOKOKU_NO 
						  AND SYONIN_HANTEI_KB = '0')),'') AS GEN_TANTO_ID			--承認担当者ID（現処置担当者ID）
	,isnull((SELECT SIMEI FROM M004_SYAIN
	  WHERE 
	  SYAIN_ID = (SELECT SYAIN_ID FROM D004_SYONIN_J_KANRI 
				 WHERE SYONIN_HOKOKUSYO_ID = 6
				  AND HOKOKU_NO = D013.HOKOKU_NO 
				  AND SYONIN_JUN = (SELECT MIN(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
									WHERE SYONIN_HOKOKUSYO_ID = 6
									AND HOKOKU_NO = D014.HOKOKU_NO 
									AND SYONIN_HANTEI_KB = '0'))),'')	AS GEN_TANTO_NAME	--承認担当者名
	,ISNULL((SELECT MAX(UPD_YMDHNS) FROM D004_SYONIN_J_KANRI
	  WHERE SYONIN_HOKOKUSYO_ID = 6
	   AND HOKOKU_NO = D014.HOKOKU_NO
		 AND SYONIN_HANTEI_KB = '1'),'') AS SYONIN_YMDHNS							--承認日時（処置実施日および前処置実施日）		 
	,CASE D014.CLOSE_FG 
	 WHEN '0' THEN
		dbo.SC02_GET_TAIRYU_NISSU('1'
							   ,(SELECT MAX(CASE WHEN UPD_YMDHNS='' THEN ADD_YMDHNS ELSE UPD_YMDHNS END) FROM D004_SYONIN_J_KANRI
								 WHERE SYONIN_HOKOKUSYO_ID = 6
								  AND HOKOKU_NO = D014.HOKOKU_NO
									AND SYONIN_HANTEI_KB = '0')
							   ,CONVERT(nvarchar,GETDATE(),112)
								 )
	ELSE '0'
	END		AS TAIRYU_NISSU									--滞留日数	
	,dbo.SC02_GET_TAIRYU_NISSU('1',SUBSTRING(D013.ADD_YMDHNS,1,8),CONVERT(nvarchar,GETDATE(),112)) TOTAL_TAIRYU_NISSU	--累計滞留日数
	,CASE D014.CLOSE_FG 
	 WHEN '0' THEN
		CASE WHEN dbo.SC02_GET_TAIRYU_NISSU('1'
										,(SELECT MAX(CASE WHEN UPD_YMDHNS='' THEN ADD_YMDHNS ELSE UPD_YMDHNS END) FROM D004_SYONIN_J_KANRI
										  WHERE SYONIN_HOKOKUSYO_ID = 6
										  AND HOKOKU_NO = D014.HOKOKU_NO
														AND SYONIN_HANTEI_KB = '0')
										 ,CONVERT(nvarchar,GETDATE(),112)) >= (SELECT KEIKOKU_TAIRYU_NISSU FROM M014_SYONIN_ROUT 
																				WHERE SYONIN_HOKOKUSYO_ID = 6
																				AND SYONIN_JUN = (SELECT MAX(SYONIN_JUN) FROM D004_SYONIN_J_KANRI 
																								  WHERE SYONIN_HOKOKUSYO_ID = 6
																									AND HOKOKU_NO = D014.HOKOKU_NO 
																									AND SYONIN_HANTEI_KB = '0')) THEN '1'
		 ELSE '0' END 
	 ELSE 0 END	 AS TAIRYU_FG		--滞留フラグ
  , D014.CLOSE_FG
  , D014.BUMON_KB
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '部門区分' AND ITEM_VALUE=D014.BUMON_KB),'') AS BUMON_NAME	----部門区分名
  , D014.BUSYO_ID
  , isnull((SELECT BUSYO_NAME FROM M002_BUSYO AS M002 WHERE M002.BUSYO_ID = D014.BUSYO_ID), '') AS BUSYO_NAME
  , D014.TANTO_ID 
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D014.TANTO_ID = M.SYAIN_ID)),'') AS TANTO_NAME
  , D013.INPUT_TYPE
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = '是正処置区分' AND ITEM_VALUE=D013.INPUT_TYPE),'') AS INPUT_TYPE_DISP
  , D013.DOC_NO
  , D014.KAITOU_KIBOU_YMD
  , D014.KANSATU_HOUKOKU 
  , D014.ZESEI_RIYU 
  , D014.ZESEI_COMMENT
  , D014.KAITOU_YMD
  , D014.FUTEKIGO_TAISYOU
  , D014.CHOUSA_HANI
  , D014.FUTEKIGO_UMU
  , D014.EIKYOU_HANI
  , D014.OUKYU_SYOCHI
  , D014.OUKYU_SYOCHI_YOTEI_YMD
  , D014.JINTEKI_YOUIN_UMU
  , D014.HASSEI_GENIN
  , D014.ZESEI_SYOCHI
  , D014.ZESEI_SYOCHI_YOTEI_YMD
  , D014.ZESEI_SYOCHI_YMD
  , D014.OUKYU_SYOCHI_YMD
  , D014.OUKYU_SYOCHI_KEKKA
  , D014.ZESEI_SYOCHI_KEKKA
  , D014.ZESEI_SYOCHI_HANTEI
  , D014.ZESEI_SYOCHI_NG_DOC_NO
  , D014.FILE_PATH1
  , D014.FILE_PATH2
  , D014.FILE_PATH3
  , D014.FILE_PATH4
  , D014.FILE_PATH5
  , D014.COMMENT1
  , D014.COMMENT2
  , D014.COMMENT3
  , D014.COMMENT4
  , D014.COMMENT5
  , D014.ADD_YMDHNS
  , D014.ADD_SYAIN_ID
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D014.ADD_SYAIN_ID = M.SYAIN_ID)),'') AS ADD_TANTO_NAME
  , D014.DEL_YMDHNS
  , D014.DEL_SYAIN_ID  
FROM
D014_ZESEI_RYUSYUTU_J D014
INNER JOIN D013_ZESEI_HASSEI_J D013
ON (D014.HOKOKU_NO = D013.HOKOKU_NO)