ALTER VIEW dbo.V016_ZESEI_HASSEI AS 
SELECT
    D013.HOKOKU_NO	 
  , D013.CLOSE_FG
  , D013.BUMON_KB
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'ïîñÂãÊï™' AND ITEM_VALUE=D013.BUMON_KB),'') AS BUMON_NAME	----ïîñÂãÊï™ñº
  , D013.BUSYO_ID
  , isnull((SELECT BUSYO_NAME FROM M002_BUSYO AS M002 WHERE M002.BUSYO_ID = D013.BUSYO_ID), '') AS BUSYO_NAME
  , D013.TANTO_ID 
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D013.TANTO_ID = M.SYAIN_ID)),'') AS TANTO_NAME
  , D013.INPUT_TYPE
  , isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'ê•ê≥èàíuãÊï™' AND ITEM_VALUE=D013.INPUT_TYPE),'') AS INPUT_TYPE_DISP
  , D013.DOC_NO
  , D013.KAITOU_KIBOU_YMD
  , D013.KANSATU_HOUKOKU 
  , D013.ZESEI_RIYU 
  , D013.ZESEI_COMMENT
  , D013.KAITOU_YMD
  , D013.FUTEKIGO_TAISYOU
  , D013.CHOUSA_HANI
  , D013.FUTEKIGO_UMU
  , D013.EIKYOU_HANI
  , D013.OUKYU_SYOCHI
  , D013.OUKYU_SYOCHI_YOTEI_YMD
  , D013.JINTEKI_YOUIN_UMU
  , D013.HASSEI_GENIN
  , D013.ZESEI_SYOCHI
  , D013.ZESEI_SYOCHI_YOTEI_YMD
  , D013.ZESEI_SYOCHI_YMD
  , D013.OUKYU_SYOCHI_YMD
  , D013.OUKYU_SYOCHI_KEKKA
  , D013.ZESEI_SYOCHI_KEKKA
  , D013.ZESEI_SYOCHI_HANTEI
  , D013.ZESEI_SYOCHI_NG_DOC_NO
  , D013.FILE_PATH1
  , D013.FILE_PATH2
  , D013.FILE_PATH3
  , D013.FILE_PATH4
  , D013.FILE_PATH5
  , D013.COMMENT1
  , D013.COMMENT2
  , D013.COMMENT3
  , D013.COMMENT4
  , D013.COMMENT5
  , D013.ADD_YMDHNS
  , D013.ADD_SYAIN_ID
  , ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(D013.ADD_SYAIN_ID = M.SYAIN_ID)),'') AS ADD_TANTO_NAME
  , D013.DEL_YMDHNS
  , D013.DEL_SYAIN_ID
  ,ISNULL((SELECT CASE WHEN SYONIN_YMDHNS <> '' THEN UPD_SYAIN_NAME ELSE SYAIN_NAME	END FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 10),'') AS SYONIN_NAME10
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =10),'') AS SYONIN_YMD10
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 11),'') AS SYONIN_NAME11
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =11),'') AS SYONIN_YMD11
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 12),'') AS SYONIN_NAME12
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =12),'') AS SYONIN_YMD12
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 20),'') AS SYONIN_NAME20
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =20),'') AS SYONIN_YMD20
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 21),'') AS SYONIN_NAME21
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =21),'') AS SYONIN_YMD21
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 22),'') AS SYONIN_NAME22
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =22),'') AS SYONIN_YMD22
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 23),'') AS SYONIN_NAME23
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =23),'') AS SYONIN_YMD23
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 24),'') AS SYONIN_NAME24
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =24),'') AS SYONIN_YMD24
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 30),'') AS SYONIN_NAME30
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =30),'') AS SYONIN_YMD30
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 31),'') AS SYONIN_NAME31
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =31),'') AS SYONIN_YMD31
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 32),'') AS SYONIN_NAME32
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =32),'') AS SYONIN_YMD32
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 40),'') AS SYONIN_NAME40
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =40),'') AS SYONIN_YMD40
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 41),'') AS SYONIN_NAME41
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =41),'') AS SYONIN_YMD41
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 42),'') AS SYONIN_NAME42
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =42),'') AS SYONIN_YMD42
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 50),'') AS SYONIN_NAME50
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =50),'') AS SYONIN_YMD50
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 51),'') AS SYONIN_NAME51
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =51),'') AS SYONIN_YMD51
  ,ISNULL((SELECT SYAIN_NAME FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN = 52),'') AS SYONIN_NAME52
  ,ISNULL((SELECT SUBSTRING(SYONIN_YMDHNS,1,8) FROM V003_SYONIN_J_KANRI
		 WHERE SYONIN_HOKOKUSYO_ID = 5 AND HOKOKU_NO = D013.HOKOKU_NO AND SYONIN_JUN =52),'') AS SYONIN_YMD52

FROM
  D013_ZESEI_HASSEI_J D013