ALTER VIEW [dbo].[VWM002_BUSYO]
AS
SELECT
 M002.BUSYO_ID
,M002.BUMON_KB
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'ïîñÂãÊï™' AND ITEM_VALUE = M002.BUMON_KB),'') AS BUMON_KB_NAME
,M002.YUKO_YMD
,M002.BUSYO_KB
,isnull((SELECT ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = 'ïîèêãÊï™' AND ITEM_VALUE = M002.BUSYO_KB),'') AS BUSYO_KB_NAME
,M002.BUSYO_NAME
,isnull((select isnull(BUSYO_KB,'') FROM M002_BUSYO WHERE BUSYO_ID = M002.OYA_BUSYO_ID),'') AS OYA_BUSYO_KB
,M002.OYA_BUSYO_ID
,isnull((SELECT BUSYO_NAME FROM M002_BUSYO AS M WHERE(M002.OYA_BUSYO_ID = M.BUSYO_ID)),'') AS OYA_BUSYO_NAME
,M002.SYOZOKUCYO_ID
,isnull((SELECT SYAIN_NO FROM M004_SYAIN AS M WHERE(M002.SYOZOKUCYO_ID = M.SYAIN_ID)),'') AS SYOZOKUCYO_SYAIN_NO
,isnull((SELECT SIMEI FROM M004_SYAIN AS M WHERE(M002.SYOZOKUCYO_ID = M.SYAIN_ID)),'') AS SYOZOKUCYO_SYAIN_NAME
,M002.TEL
,M002.ADD_YMDHNS
,M002.ADD_SYAIN_ID
,ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(M002.ADD_SYAIN_ID = M.SYAIN_ID)),'') AS ADD_SYAIN_NAME
,M002.UPD_YMDHNS
,M002.UPD_SYAIN_ID
,ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(M002.UPD_SYAIN_ID = M.SYAIN_ID)),'') AS UPD_SYAIN_NAME
,M002.DEL_YMDHNS
,M002.DEL_SYAIN_ID
,ISNULL((SELECT SIMEI FROM M004_SYAIN AS M WHERE(M002.DEL_SYAIN_ID = M.SYAIN_ID)),'') AS DEL_SYAIN_NAME
,(CASE M002.DEL_YMDHNS WHEN ' ' THEN '0' ELSE '1' END) AS DEL_FLG
FROM
  M002_BUSYO AS M002