USE [FMS]
GO

/****** Object:  UserDefinedFunction [dbo].[SC04_GET_FUTEKIGO_S_KB_DISP]    Script Date: 2018/10/11 14:39:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================

ALTER function [dbo].[SC04_GET_FUTEKIGO_S_KB_DISP](
	@BUMON_KB char(1),
	@FUTEKIGO_KB char(1),
	@FUTEKIGO_S_KB char(3)) returns nvarchar(150)
AS
BEGIN
	
	DECLARE @TAG		nvarchar(10);
	DECLARE @ITEM_DISP  nvarchar(150);

	SET @ITEM_DISP = '';

	IF @BUMON_KB = '1'		--風防
	BEGIN
		SET @TAG = '風防_不適合';
		
		IF @FUTEKIGO_KB = '0'	--外観
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '外観区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '1'	--寸法
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '寸法区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '2'	--形状
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '形状区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '3'	--機能・性能
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '機能性能区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '9'	--その他
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + 'その他区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE
			SET @ITEM_DISP = '';
	END
	ELSE IF @BUMON_KB = '3' --複合材	
	BEGIN
		SET @TAG = '複合材_不適合';
		IF @FUTEKIGO_KB = '0'	--寸法
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '寸法区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '1'	--形状
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '形状区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '2'	--穿孔
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '穿孔区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '3'	--外観
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '外観区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '4'	--内部欠陥
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '内部欠陥区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '5'	--硬化条件
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '硬化条件区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '6'	--プロセス
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + 'プロセス区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '9'	--その他
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + 'その他区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE
			SET @ITEM_DISP = '';
	END
	ELSE IF @BUMON_KB = '2' --LP	
	BEGIN
		SET @TAG = 'LP_不適合';

		IF @FUTEKIGO_KB = '0'	--外観
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '外観区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '1'	--寸法
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '寸法区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '2'	--形状
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '形状区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '3'	--機能・性能
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + '機能性能区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE IF @FUTEKIGO_KB = '9'	--その他
			SELECT @ITEM_DISP = ITEM_DISP FROM M001_SETTING WHERE ITEM_NAME = @TAG + 'その他区分' AND ITEM_VALUE = @FUTEKIGO_S_KB
		ELSE
			SET @ITEM_DISP = '';
	END

	RETURN @ITEM_DISP;

END


GO

