USE [FMS]
GO
/****** Object:  UserDefinedFunction [dbo].[TV01_HENKO_HIKAKU]    Script Date: 2019/01/30 9:45:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



-- =============================================
-- Author:		JMS-
-- Create date: 2018.
-- Description:	変更内容比較一覧
-- =============================================
ALTER FUNCTION [dbo].[TV01_HENKO_HIKAKU] 
(
	 @SASIMODOSI_YMDHNS		char(14)	--差戻日時
	,@SYONIN_HOKOKUSYO_ID	int			--承認報告書ID
	,@HOKOKUSYO_NO			char(10)	--報告書No
) RETURNS
	@retTBL TABLE(
	 KOMOKU_NAME	nvarchar(100)					--項目名
	,MAE_NAIYO		nvarchar(500)				--変更前内容
	,ATO_NAIYO		nvarchar(500)				--変更後内容留日数
)
AS
BEGIN
	--R003_NCR_SASIMODOSI 
	DECLARE @WNJ_HOKOKU_NO					char(10);
	DECLARE @WNJ_BUMON_KB					char(1);
	DECLARE @WNJ_BUMON_NAME					nvarchar(150);
	DECLARE @WNJ_CLOSE_FG					char(1);
	DECLARE @WNJ_KISYU_ID					int;
	--DECLARE @WNJ_KISYU						nvarchar(30);
	DECLARE @WNJ_KISYU_NAME					nvarchar(30);
	DECLARE @WNJ_SYANAI_CD					nvarchar(10);
	DECLARE @WNJ_BUHIN_BANGO					varchar(60);
	DECLARE @WNJ_BUHIN_NAME					nvarchar(50);
	DECLARE @WNJ_GOKI						nvarchar(20);
	DECLARE @WNJ_SURYO						int;
	DECLARE @WNJ_SAIHATU						varchar(10);
	DECLARE @WNJ_FUTEKIGO_JYOTAI_KB			char(1);
	DECLARE @WNJ_FUTEKIGO_JYOTAI_NAME		nvarchar(150);
	DECLARE @WNJ_FUTEKIGO_NAIYO				nvarchar(30);
	DECLARE @WNJ_FUTEKIGO_KB					char(1);
	DECLARE @WNJ_FUTEKIGO_NAME				nvarchar(150);
	DECLARE @WNJ_FUTEKIGO_S_KB				varchar(2);
	DECLARE @WNJ_FUTEKIGO_S_NAME				nvarchar(150);
	DECLARE @WNJ_ZUMEN_KIKAKU				nvarchar(30);
	DECLARE @WNJ_YOKYU_NAIYO					nvarchar(500);
	DECLARE @WNJ_KANSATU_KEKKA				nvarchar(500);
	DECLARE @WNJ_ZESEI_SYOCHI_YOHI_KB		char(1);
	DECLARE @WNJ_ZESEI_SYOCHI_YOHI_NAME		nvarchar(150);
	DECLARE @WNJ_ZESEI_NASI_RIYU				nvarchar(100);
	DECLARE @WNJ_JIZEN_SINSA_HANTEI_KB		char(1);
	DECLARE @WNJ_JIZEN_SINSA_HANTEI_NAME		nvarchar(150);
	DECLARE @WNJ_JIZEN_SINSA_SYAIN_ID		int;
	DECLARE @WNJ_JIZEN_SINSA_SYAIN_NAME		nvarchar(30);
	DECLARE @WNJ_JIZEN_SINSA_YMD				char(8);
	DECLARE @WNJ_SAISIN_KAKUNIN_SYAIN_ID		int;
	DECLARE @WNJ_SAISIN_KAKUNIN_SYAIN_NAME	nvarchar(30);
	DECLARE @WNJ_SAISIN_KAKUNIN_YMD			char(8);
	DECLARE @WNJ_SAISIN_IINKAI_HANTEI_KB		char(1);
	DECLARE @WNJ_SAISIN_IINKAI_HANTEI_NAME	nvarchar(150);
	DECLARE @WNJ_SAISIN_GIJYUTU_SYAIN_ID		int;
	DECLARE @WNJ_SAISIN_GIJYUTU_SYAIN_NAME	nvarchar(30);
	DECLARE @WNJ_SAISIN_GIJYUTU_YMD			char(8);
	DECLARE @WNJ_SAISIN_HINSYO_SYAIN_ID		int;
	DECLARE @WNJ_SAISIN_HINSYO_SYAIN_NAME	nvarchar(30);
	DECLARE @WNJ_SAISIN_HINSYO_YMD			char(8);
	DECLARE @WNJ_SAISIN_IINKAI_SIRYO_NO		char(2);
	DECLARE @WNJ_ITAG_NO						nvarchar(20);
	DECLARE @WNJ_KOKYAKU_SAISIN_TANTO_ID		int;
	DECLARE @WNJ_KOKYAKU_SAISIN_TANTO_NAME	nvarchar(30);
	DECLARE @WNJ_KOKYAKU_SAISIN_YMD			char(8);
	DECLARE @WNJ_KOKYAKU_HANTEI_SIJI_KB		char(1);
	DECLARE @WNJ_KOKYAKU_HANTEI_SIJI_NAME	nvarchar(150);
	DECLARE @WNJ_KOKYAKU_HANTEI_SIJI_YMD		char(8);
	
	DECLARE @WNJ_KOKYAKU_SAISIN_FILEPATH1	nvarchar(200);
	DECLARE @WNJ_KOKYAKU_SAISIN_FILEPATH2	nvarchar(200);

	DECLARE @WNJ_KOKYAKU_SAISYU_HANTEI_KB	char(1);
	DECLARE @WNJ_KOKYAKU_SAISYU_HANTEI_NAME	nvarchar(150);
	DECLARE @WNJ_KOKYAKU_SAISYU_HANTEI_YMD	char(8);
	DECLARE @WNJ_SAIKAKO_SIJI_FG				char(1);
	DECLARE @WNJ_HAIKYAKU_YMD				char(8);
	DECLARE @WNJ_HAIKYAKU_KB					char(1);
	DECLARE @WNJ_HAIKYAKU_KB_NAME			nvarchar(150);
	DECLARE @WNJ_HAIKYAKU_HOUHOU				nvarchar(30);
	DECLARE @WNJ_HAIKYAKU_TANTO_ID			int;
	DECLARE @WNJ_HAIKYAKU_TANTO_NAME			nvarchar(150);
	DECLARE @WNJ_SAIKAKO_SIJI_NO				char(10);
	DECLARE @WNJ_SAIKAKO_SAGYO_KAN_YMD		char(8);
	DECLARE @WNJ_SAIKAKO_KENSA_YMD			char(8);
	DECLARE @WNJ_KENSA_KEKKA_KB				char(1);
	DECLARE @WNJ_KENSA_KEKKA_NAME			nvarchar(150);
	DECLARE @WNJ_SEIGI_TANTO_ID				int;
	DECLARE @WNJ_SEIGI_TANTO_NAME			nvarchar(30);
	DECLARE @WNJ_SEIZO_TANTO_ID				int;
	DECLARE @WNJ_SEIZO_TANTO_NAME			nvarchar(30);
	DECLARE @WNJ_KENSA_TANTO_ID				int;
	DECLARE @WNJ_KENSA_TANTO_NAME			nvarchar(30);
	DECLARE @WNJ_HENKYAKU_YMD				char(8);
	DECLARE @WNJ_HENKYAKU_SAKI				nvarchar(60);
	DECLARE @WNJ_HENKYAKU_TANTO_ID			int;
	DECLARE @WNJ_HENKYAKU_TANTO_NAME			nvarchar(30);
	DECLARE @WNJ_HENKYAKU_BIKO				nvarchar(100);
	DECLARE @WNJ_TENYO_KISYU_ID				int;
	--DECLARE @WNJ_TENYO_KISYU					nvarchar(30);
	DECLARE @WNJ_TENYO_KISYU_NAME			nvarchar(30);
	DECLARE @WNJ_TENYO_BUHIN_BANGO			varchar(60);
	DECLARE @WNJ_TENYO_GOKI					nvarchar(20);
	DECLARE @WNJ_TENYO_LOT					int;
	DECLARE @WNJ_TENYO_YMD					char(8);
	DECLARE @WNJ_SYOCHI_KEKKA_A				char(1);
	DECLARE @WNJ_SYOCHI_KEKKA_A_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_KEKKA_B				char(1);
	DECLARE @WNJ_SYOCHI_KEKKA_B_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_KEKKA_C				char(1);
	DECLARE @WNJ_SYOCHI_KEKKA_C_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_D_UMU_KB				char(1);
	DECLARE @WNJ_SYOCHI_D_UMU_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_D_YOHI_KB			char(1);
	DECLARE @WNJ_SYOCHI_D_YOHI_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_D_SYOCHI_KIROKU		nvarchar(100);
	DECLARE @WNJ_SYOCHI_E_UMU_KB				char(1);
	DECLARE @WNJ_SYOCHI_E_UMU_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_E_YOHI_KB			char(1);
	DECLARE @WNJ_SYOCHI_E_YOHI_NAME			nvarchar(150);
	DECLARE @WNJ_SYOCHI_E_SYOCHI_KIROKU		nvarchar(100);
	DECLARE @WNJ_FILE_PATH					nvarchar(200);
	DECLARE @WNJ_G_FILE_PATH1				nvarchar(200);
	DECLARE @WNJ_G_FILE_PATH2				nvarchar(200);
	DECLARE @WNJ_HASSEI_KOTEI_GL_SYAIN_ID				int;
	DECLARE @WNJ_HASSEI_KOTEI_GL_SYAIN_NAME				nvarchar(30);
		

	--R003_NCR_SASIMODOSI		
	DECLARE @WNR_HOKOKU_NO					char(10);
	DECLARE @WNR_BUMON_KB					char(1);
	DECLARE @WNR_BUMON_NAME					nvarchar(150);
	DECLARE @WNR_CLOSE_FG					char(1);
	DECLARE @WNR_KISYU_ID					int;
	--DECLARE @WNR_KISYU						nvarchar(30);
	DECLARE @WNR_KISYU_NAME					nvarchar(30);
	DECLARE @WNR_SYANAI_CD					nvarchar(10);
	DECLARE @WNR_BUHIN_BANGO					varchar(60);
	DECLARE @WNR_BUHIN_NAME					nvarchar(50);
	DECLARE @WNR_GOKI						nvarchar(20);
	DECLARE @WNR_SURYO						int;
	DECLARE @WNR_SAIHATU						varchar(10);
	DECLARE @WNR_FUTEKIGO_JYOTAI_KB			char(1);
	DECLARE @WNR_FUTEKIGO_JYOTAI_NAME		nvarchar(150);
	DECLARE @WNR_FUTEKIGO_NAIYO				nvarchar(30);
	DECLARE @WNR_FUTEKIGO_KB					char(1);
	DECLARE @WNR_FUTEKIGO_NAME				nvarchar(150);
	DECLARE @WNR_FUTEKIGO_S_KB				varchar(2);
	DECLARE @WNR_FUTEKIGO_S_NAME				nvarchar(150);
	DECLARE @WNR_ZUMEN_KIKAKU				nvarchar(30);
	DECLARE @WNR_YOKYU_NAIYO					nvarchar(500);
	DECLARE @WNR_KANSATU_KEKKA				nvarchar(500);
	DECLARE @WNR_ZESEI_SYOCHI_YOHI_KB		char(1);
	DECLARE @WNR_ZESEI_SYOCHI_YOHI_NAME		nvarchar(150);
	DECLARE @WNR_ZESEI_NASI_RIYU				nvarchar(100);
	DECLARE @WNR_JIZEN_SINSA_HANTEI_KB		char(1);
	DECLARE @WNR_JIZEN_SINSA_HANTEI_NAME		nvarchar(150);
	DECLARE @WNR_JIZEN_SINSA_SYAIN_ID		int;
	DECLARE @WNR_JIZEN_SINSA_SYAIN_NAME		nvarchar(30);
	DECLARE @WNR_JIZEN_SINSA_YMD				char(8);
	DECLARE @WNR_SAISIN_KAKUNIN_SYAIN_ID		int;
	DECLARE @WNR_SAISIN_KAKUNIN_SYAIN_NAME	nvarchar(30);
	DECLARE @WNR_SAISIN_KAKUNIN_YMD			char(8);
	DECLARE @WNR_SAISIN_IINKAI_HANTEI_KB		char(1);
	DECLARE @WNR_SAISIN_IINKAI_HANTEI_NAME	nvarchar(150);
	DECLARE @WNR_SAISIN_GIJYUTU_SYAIN_ID		int;
	DECLARE @WNR_SAISIN_GIJYUTU_SYAIN_NAME	nvarchar(30);
	DECLARE @WNR_SAISIN_GIJYUTU_YMD			char(8);
	DECLARE @WNR_SAISIN_HINSYO_SYAIN_ID		int;
	DECLARE @WNR_SAISIN_HINSYO_SYAIN_NAME	nvarchar(30);
	DECLARE @WNR_SAISIN_HINSYO_YMD			char(8);
	DECLARE @WNR_SAISIN_IINKAI_SIRYO_NO		char(2);
	DECLARE @WNR_ITAG_NO						nvarchar(20);
	DECLARE @WNR_KOKYAKU_SAISIN_TANTO_ID		int;
	DECLARE @WNR_KOKYAKU_SAISIN_TANTO_NAME	nvarchar(30);
	DECLARE @WNR_KOKYAKU_SAISIN_YMD			char(8);

	DECLARE @WNR_KOKYAKU_SAISIN_FILEPATH1	nvarchar(200);
	DECLARE @WNR_KOKYAKU_SAISIN_FILEPATH2	nvarchar(200);

	DECLARE @WNR_KOKYAKU_HANTEI_SIJI_KB		char(1);
	DECLARE @WNR_KOKYAKU_HANTEI_SIJI_NAME	nvarchar(150);
	DECLARE @WNR_KOKYAKU_HANTEI_SIJI_YMD		char(8);
	DECLARE @WNR_KOKYAKU_SAISYU_HANTEI_KB	char(1);
	DECLARE @WNR_KOKYAKU_SAISYU_HANTEI_NAME	nvarchar(150);
	DECLARE @WNR_KOKYAKU_SAISYU_HANTEI_YMD	char(8);
	DECLARE @WNR_SAIKAKO_SIJI_FG				char(1);
	DECLARE @WNR_HAIKYAKU_YMD				char(8);
	DECLARE @WNR_HAIKYAKU_KB					char(1);
	DECLARE @WNR_HAIKYAKU_KB_NAME			nvarchar(150);
	DECLARE @WNR_HAIKYAKU_HOUHOU				nvarchar(30);
	DECLARE @WNR_HAIKYAKU_TANTO_ID			int;
	DECLARE @WNR_HAIKYAKU_TANTO_NAME			nvarchar(150);
	DECLARE @WNR_SAIKAKO_SIJI_NO				char(10);
	DECLARE @WNR_SAIKAKO_SAGYO_KAN_YMD		char(8);
	DECLARE @WNR_SAIKAKO_KENSA_YMD			char(8);
	DECLARE @WNR_KENSA_KEKKA_KB				char(1);
	DECLARE @WNR_KENSA_KEKKA_NAME			nvarchar(150);
	DECLARE @WNR_SEIGI_TANTO_ID				int;
	DECLARE @WNR_SEIGI_TANTO_NAME			nvarchar(30);
	DECLARE @WNR_SEIZO_TANTO_ID				int;
	DECLARE @WNR_SEIZO_TANTO_NAME			nvarchar(30);
	DECLARE @WNR_KENSA_TANTO_ID				int;
	DECLARE @WNR_KENSA_TANTO_NAME			nvarchar(30);
	DECLARE @WNR_HENKYAKU_YMD				char(8);
	DECLARE @WNR_HENKYAKU_SAKI				nvarchar(60);
	DECLARE @WNR_HENKYAKU_TANTO_ID			int;
	DECLARE @WNR_HENKYAKU_TANTO_NAME			nvarchar(30);
	DECLARE @WNR_HENKYAKU_BIKO				nvarchar(100);
	DECLARE @WNR_TENYO_KISYU_ID				int;
	--DECLARE @WNR_TENYO_KISYU					nvarchar(30);
	DECLARE @WNR_TENYO_KISYU_NAME			nvarchar(30);
	DECLARE @WNR_TENYO_BUHIN_BANGO			varchar(60);
	DECLARE @WNR_TENYO_GOKI					nvarchar(20);
	DECLARE @WNR_TENYO_LOT					int;
	DECLARE @WNR_TENYO_YMD					char(8);
	DECLARE @WNR_SYOCHI_KEKKA_A				char(1);
	DECLARE @WNR_SYOCHI_KEKKA_A_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_KEKKA_B				char(1);
	DECLARE @WNR_SYOCHI_KEKKA_B_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_KEKKA_C				char(1);
	DECLARE @WNR_SYOCHI_KEKKA_C_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_D_UMU_KB				char(1);
	DECLARE @WNR_SYOCHI_D_UMU_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_D_YOHI_KB			char(1);
	DECLARE @WNR_SYOCHI_D_YOHI_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_D_SYOCHI_KIROKU		nvarchar(100);
	DECLARE @WNR_SYOCHI_E_UMU_KB				char(1);
	DECLARE @WNR_SYOCHI_E_UMU_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_E_YOHI_KB			char(1);
	DECLARE @WNR_SYOCHI_E_YOHI_NAME			nvarchar(150);
	DECLARE @WNR_SYOCHI_E_SYOCHI_KIROKU		nvarchar(100);
	DECLARE @WNR_FILE_PATH					nvarchar(200);
	DECLARE @WNR_G_FILE_PATH1				nvarchar(200);
	DECLARE @WNR_G_FILE_PATH2				nvarchar(200);
	DECLARE @WNR_HASSEI_KOTEI_GL_SYAIN_ID				int;
	DECLARE @WNR_HASSEI_KOTEI_GL_SYAIN_NAME				nvarchar(30);

	--V005_CAR_J
	DECLARE @WCJ_HOKOKU_NO				char(10);	
	DECLARE @WCJ_BUMON_KB				char(2);
	DECLARE @WCJ_BUMON_NAME				nvarchar(150);
	DECLARE @WCJ_CLOSE_FG				char(1);
	DECLARE @WCJ_SETUMON_1				nvarchar(100);
	DECLARE @WCJ_KAITO_1				nvarchar(200);
	DECLARE @WCJ_SETUMON_2				nvarchar(100);
	DECLARE @WCJ_KAITO_2				nvarchar(200);
	DECLARE @WCJ_SETUMON_3				nvarchar(100);
	DECLARE @WCJ_KAITO_3				nvarchar(200);	
	DECLARE @WCJ_SETUMON_4				nvarchar(100);
	DECLARE @WCJ_KAITO_4				nvarchar(200);
	DECLARE @WCJ_SETUMON_5				nvarchar(100);
	DECLARE @WCJ_KAITO_5				nvarchar(200);
	DECLARE @WCJ_SETUMON_6				nvarchar(100);
	DECLARE @WCJ_KAITO_6				nvarchar(200);
	DECLARE @WCJ_SETUMON_7				nvarchar(100);	
	DECLARE @WCJ_KAITO_7				nvarchar(200);	
	DECLARE @WCJ_SETUMON_8				nvarchar(100);
	DECLARE @WCJ_KAITO_8				nvarchar(150);
	DECLARE @WCJ_SETUMON_9				nvarchar(100);
	DECLARE @WCJ_KAITO_9				nvarchar(150);
	DECLARE @WCJ_SETUMON_10				nvarchar(100);
	DECLARE @WCJ_KAITO_10				nvarchar(150);
	DECLARE @WCJ_SETUMON_11				nvarchar(100);
	DECLARE @WCJ_KAITO_11				nvarchar(150);
	DECLARE @WCJ_SETUMON_12				nvarchar(100);
	DECLARE @WCJ_KAITO_12				nvarchar(150);	
	DECLARE @WCJ_SETUMON_13				nvarchar(100);
	DECLARE @WCJ_KAITO_13				nvarchar(150);
	DECLARE @WCJ_SETUMON_14				nvarchar(100);
	DECLARE @WCJ_KAITO_14				nvarchar(150);
	DECLARE @WCJ_SETUMON_15				nvarchar(100);
	DECLARE @WCJ_KAITO_15				nvarchar(150);
	DECLARE @WCJ_SETUMON_16				nvarchar(100);
	DECLARE @WCJ_KAITO_16				nvarchar(150);
	DECLARE @WCJ_SETUMON_17				nvarchar(100);	
	DECLARE @WCJ_KAITO_17				nvarchar(150);
	DECLARE @WCJ_SETUMON_18				nvarchar(100);
	DECLARE @WCJ_KAITO_18				nvarchar(150);
	DECLARE @WCJ_SETUMON_19				nvarchar(100);
	DECLARE @WCJ_KAITO_19				nvarchar(150);
	DECLARE @WCJ_SETUMON_20				nvarchar(100);
	DECLARE @WCJ_KAITO_20				nvarchar(150);
	DECLARE @WCJ_SETUMON_21				nvarchar(100);
	DECLARE @WCJ_KAITO_21				nvarchar(150);
	DECLARE @WCJ_SETUMON_22				nvarchar(100);
	DECLARE @WCJ_KAITO_22				nvarchar(150);
	DECLARE @WCJ_SETUMON_23				nvarchar(100);
	DECLARE @WCJ_KAITO_23				nvarchar(150);
	DECLARE @WCJ_SETUMON_24				nvarchar(100);
	DECLARE @WCJ_KAITO_24				nvarchar(150);
	DECLARE @WCJ_SETUMON_25				nvarchar(100);
	DECLARE @WCJ_KAITO_25				nvarchar(150);	
	DECLARE @WCJ_KONPON_YOIN_KB1		char(2);	
	DECLARE @WCJ_KONPON_YOIN_NAME1		nvarchar(150);
	DECLARE @WCJ_KONPON_YOIN_KB2		char(2);	
	DECLARE @WCJ_KONPON_YOIN_NAME2		nvarchar(150);	
	DECLARE @WCJ_KONPON_YOIN_SYAIN_ID	int;
	DECLARE @WCJ_KONPON_YOIN_SYAIN_NAME	nvarchar(30);
	DECLARE @WCJ_KISEKI_KOTEI_KB		char(2);
	DECLARE @WCJ_KISEKI_KOTEI_NAME		nvarchar(150);
	DECLARE @WCJ_SYOCHI_A_SYAIN_ID		int;
	DECLARE @WCJ_SYOCHI_A_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCJ_SYOCHI_A_YMDHNS		char(14);
	DECLARE @WCJ_SYOCHI_B_SYAIN_ID		int;
	DECLARE @WCJ_SYOCHI_B_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCJ_SYOCHI_B_YMDHNS		char(14);
	DECLARE @WCJ_SYOCHI_C_SYAIN_ID		int;
	DECLARE @WCJ_SYOCHI_C_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCJ_SYOCHI_C_YMDHNS		char(14);
	DECLARE @WCJ_KYOIKU_FILE_PATH		nvarchar(200);
	DECLARE @WCJ_ZESEI_SYOCHI_YUKO_UMU	char(2);
	DECLARE @WCJ_SYOSAI_FILE_PATH		nvarchar(200);
	DECLARE @WCJ_GOKI					nvarchar(20);
	DECLARE @WCJ_LOT					char(15);
	DECLARE @WCJ_KENSA_TANTO_ID			int;
	DECLARE @WCJ_KENSA_TANTO_NAME		nvarchar(30);
	DECLARE @WCJ_KENSA_TOROKU_YMDHNS	char(14);
	DECLARE @WCJ_KENSA_GL_SYAIN_ID		int;
	DECLARE @WCJ_KENSA_GL_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCJ_KENSA_GL_YMDHNS		char(14);
	DECLARE @WCJ_FILE_PATH1		nvarchar(200);
	DECLARE @WCJ_FILE_PATH2		nvarchar(200);	
	DECLARE @WCJ_FUTEKIGO_HASSEI_YMD				char(8);

	--V009_CAR_R
	DECLARE @WCR_HOKOKU_NO				char(10);	
	DECLARE @WCR_BUMON_KB				char(2);
	DECLARE @WCR_BUMON_NAME				nvarchar(150);
	DECLARE @WCR_CLOSE_FG				char(1);
	DECLARE @WCR_SETUMON_1				nvarchar(100);
	DECLARE @WCR_KAITO_1				nvarchar(200);
	DECLARE @WCR_SETUMON_2				nvarchar(100);
	DECLARE @WCR_KAITO_2				nvarchar(200);
	DECLARE @WCR_SETUMON_3				nvarchar(100);
	DECLARE @WCR_KAITO_3				nvarchar(200);	
	DECLARE @WCR_SETUMON_4				nvarchar(100);
	DECLARE @WCR_KAITO_4				nvarchar(200);
	DECLARE @WCR_SETUMON_5				nvarchar(100);
	DECLARE @WCR_KAITO_5				nvarchar(200);
	DECLARE @WCR_SETUMON_6				nvarchar(100);
	DECLARE @WCR_KAITO_6				nvarchar(200);
	DECLARE @WCR_SETUMON_7				nvarchar(100);	
	DECLARE @WCR_KAITO_7				nvarchar(200);	
	DECLARE @WCR_SETUMON_8				nvarchar(100);
	DECLARE @WCR_KAITO_8				nvarchar(150);
	DECLARE @WCR_SETUMON_9				nvarchar(100);
	DECLARE @WCR_KAITO_9				nvarchar(150);
	DECLARE @WCR_SETUMON_10				nvarchar(100);
	DECLARE @WCR_KAITO_10				nvarchar(150);
	DECLARE @WCR_SETUMON_11				nvarchar(100);
	DECLARE @WCR_KAITO_11				nvarchar(150);
	DECLARE @WCR_SETUMON_12				nvarchar(100);
	DECLARE @WCR_KAITO_12				nvarchar(150);	
	DECLARE @WCR_SETUMON_13				nvarchar(100);
	DECLARE @WCR_KAITO_13				nvarchar(150);
	DECLARE @WCR_SETUMON_14				nvarchar(100);
	DECLARE @WCR_KAITO_14				nvarchar(150);
	DECLARE @WCR_SETUMON_15				nvarchar(100);
	DECLARE @WCR_KAITO_15				nvarchar(150);
	DECLARE @WCR_SETUMON_16				nvarchar(100);
	DECLARE @WCR_KAITO_16				nvarchar(150);
	DECLARE @WCR_SETUMON_17				nvarchar(100);	
	DECLARE @WCR_KAITO_17				nvarchar(150);
	DECLARE @WCR_SETUMON_18				nvarchar(100);
	DECLARE @WCR_KAITO_18				nvarchar(150);
	DECLARE @WCR_SETUMON_19				nvarchar(100);
	DECLARE @WCR_KAITO_19				nvarchar(150);
	DECLARE @WCR_SETUMON_20				nvarchar(100);
	DECLARE @WCR_KAITO_20				nvarchar(150);
	DECLARE @WCR_SETUMON_21				nvarchar(100);
	DECLARE @WCR_KAITO_21				nvarchar(150);
	DECLARE @WCR_SETUMON_22				nvarchar(100);
	DECLARE @WCR_KAITO_22				nvarchar(150);
	DECLARE @WCR_SETUMON_23				nvarchar(100);
	DECLARE @WCR_KAITO_23				nvarchar(150);
	DECLARE @WCR_SETUMON_24				nvarchar(100);
	DECLARE @WCR_KAITO_24				nvarchar(150);
	DECLARE @WCR_SETUMON_25				nvarchar(100);
	DECLARE @WCR_KAITO_25				nvarchar(150);	
	DECLARE @WCR_KONPON_YOIN_KB1		char(2);	
	DECLARE @WCR_KONPON_YOIN_NAME1		nvarchar(150);
	DECLARE @WCR_KONPON_YOIN_KB2		char(2);	
	DECLARE @WCR_KONPON_YOIN_NAME2		nvarchar(150);	
	DECLARE @WCR_KONPON_YOIN_SYAIN_ID	int;
	DECLARE @WCR_KONPON_YOIN_SYAIN_NAME	nvarchar(30);
	DECLARE @WCR_KISEKI_KOTEI_KB		char(2);
	DECLARE @WCR_KISEKI_KOTEI_NAME		nvarchar(150);
	DECLARE @WCR_SYOCHI_A_SYAIN_ID		int;
	DECLARE @WCR_SYOCHI_A_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCR_SYOCHI_A_YMDHNS		char(14);
	DECLARE @WCR_SYOCHI_B_SYAIN_ID		int;
	DECLARE @WCR_SYOCHI_B_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCR_SYOCHI_B_YMDHNS		char(14);
	DECLARE @WCR_SYOCHI_C_SYAIN_ID		int;
	DECLARE @WCR_SYOCHI_C_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCR_SYOCHI_C_YMDHNS		char(14);
	DECLARE @WCR_KYOIKU_FILE_PATH		nvarchar(200);
	DECLARE @WCR_ZESEI_SYOCHI_YUKO_UMU	char(2);
	DECLARE @WCR_SYOSAI_FILE_PATH		nvarchar(200);
	DECLARE @WCR_GOKI					nvarchar(20);
	DECLARE @WCR_LOT					char(15);
	DECLARE @WCR_KENSA_TANTO_ID			int;
	DECLARE @WCR_KENSA_TANTO_NAME		nvarchar(30);
	DECLARE @WCR_KENSA_TOROKU_YMDHNS	char(14);
	DECLARE @WCR_KENSA_GL_SYAIN_ID		int;
	DECLARE @WCR_KENSA_GL_SYAIN_NAME	nvarchar(30);	
	DECLARE @WCR_KENSA_GL_YMDHNS		char(14);
	DECLARE @WCR_FILE_PATH1		nvarchar(200);
	DECLARE @WCR_FILE_PATH2		nvarchar(200);
	DECLARE @WCR_FUTEKIGO_HASSEI_YMD				char(8);

	--NCR
	IF @SYONIN_HOKOKUSYO_ID = 1 
	BEGIN
		 SELECT 
		 @WNJ_HOKOKU_NO	=	HOKOKU_NO
		,@WNJ_BUMON_KB	=	BUMON_KB
		,@WNJ_BUMON_NAME	=	BUMON_NAME
		,@WNJ_CLOSE_FG	=	CLOSE_FG
		,@WNJ_KISYU_ID	=	KISYU_ID
		--,@WNJ_KISYU	=	KISYU
		,@WNJ_KISYU_NAME	=	KISYU_NAME
		,@WNJ_SYANAI_CD	=	SYANAI_CD
		,@WNJ_BUHIN_BANGO	=	BUHIN_BANGO
		,@WNJ_BUHIN_NAME	=	BUHIN_NAME
		,@WNJ_GOKI	=	GOKI
		,@WNJ_SURYO	=	SURYO
		,@WNJ_SAIHATU	=	SAIHATU
		,@WNJ_FUTEKIGO_JYOTAI_KB	=	FUTEKIGO_JYOTAI_KB
		,@WNJ_FUTEKIGO_JYOTAI_NAME	=	FUTEKIGO_JYOTAI_NAME
		,@WNJ_FUTEKIGO_NAIYO	=	FUTEKIGO_NAIYO
		,@WNJ_FUTEKIGO_KB	=	FUTEKIGO_KB
		,@WNJ_FUTEKIGO_NAME	=	FUTEKIGO_NAME
		,@WNJ_FUTEKIGO_S_KB	=	FUTEKIGO_S_KB
		,@WNJ_FUTEKIGO_S_NAME	=	FUTEKIGO_S_NAME
		,@WNJ_ZUMEN_KIKAKU	=	ZUMEN_KIKAKU
		,@WNJ_YOKYU_NAIYO	=	YOKYU_NAIYO
		,@WNJ_KANSATU_KEKKA	=	KANSATU_KEKKA
		,@WNJ_ZESEI_SYOCHI_YOHI_KB	=	ZESEI_SYOCHI_YOHI_KB
		,@WNJ_ZESEI_SYOCHI_YOHI_NAME	=	ZESEI_SYOCHI_YOHI_NAME
		,@WNJ_ZESEI_NASI_RIYU	=	ZESEI_NASI_RIYU
		,@WNJ_JIZEN_SINSA_HANTEI_KB	=	JIZEN_SINSA_HANTEI_KB
		,@WNJ_JIZEN_SINSA_HANTEI_NAME	=	JIZEN_SINSA_HANTEI_NAME
		,@WNJ_JIZEN_SINSA_SYAIN_ID	=	JIZEN_SINSA_SYAIN_ID
		,@WNJ_JIZEN_SINSA_SYAIN_NAME	=	JIZEN_SINSA_SYAIN_NAME
		,@WNJ_JIZEN_SINSA_YMD	=	JIZEN_SINSA_YMD
		,@WNJ_SAISIN_KAKUNIN_SYAIN_ID	=	SAISIN_KAKUNIN_SYAIN_ID
		,@WNJ_SAISIN_KAKUNIN_SYAIN_NAME	=	SAISIN_KAKUNIN_SYAIN_NAME
		,@WNJ_SAISIN_KAKUNIN_YMD	=	SAISIN_KAKUNIN_YMD
		,@WNJ_SAISIN_IINKAI_HANTEI_KB	=	SAISIN_IINKAI_HANTEI_KB
		,@WNJ_SAISIN_IINKAI_HANTEI_NAME	=	SAISIN_IINKAI_HANTEI_NAME
		,@WNJ_SAISIN_GIJYUTU_SYAIN_ID	=	SAISIN_GIJYUTU_SYAIN_ID
		,@WNJ_SAISIN_GIJYUTU_SYAIN_NAME	=	SAISIN_GIJYUTU_SYAIN_NAME
		,@WNJ_SAISIN_GIJYUTU_YMD	=	SAISIN_GIJYUTU_YMD
		,@WNJ_SAISIN_HINSYO_SYAIN_ID	=	SAISIN_HINSYO_SYAIN_ID
		,@WNJ_SAISIN_HINSYO_SYAIN_NAME	=	SAISIN_HINSYO_SYAIN_NAME
		,@WNJ_SAISIN_HINSYO_YMD	=	SAISIN_HINSYO_YMD
		,@WNJ_SAISIN_IINKAI_SIRYO_NO	=	SAISIN_IINKAI_SIRYO_NO
		,@WNJ_ITAG_NO	=	ITAG_NO
		,@WNJ_KOKYAKU_SAISIN_TANTO_ID	=	KOKYAKU_SAISIN_TANTO_ID
		,@WNJ_KOKYAKU_SAISIN_TANTO_NAME	=	KOKYAKU_SAISIN_TANTO_NAME
		,@WNJ_KOKYAKU_SAISIN_YMD	=	KOKYAKU_SAISIN_YMD
		,@WNJ_KOKYAKU_HANTEI_SIJI_KB	=	KOKYAKU_HANTEI_SIJI_KB
		,@WNJ_KOKYAKU_HANTEI_SIJI_NAME	=	KOKYAKU_HANTEI_SIJI_NAME
		,@WNJ_KOKYAKU_HANTEI_SIJI_YMD	=	KOKYAKU_HANTEI_SIJI_YMD
		,@WNJ_KOKYAKU_SAISIN_FILEPATH1	=	KOKYAKU_SAISIN_FILEPATH1
		,@WNJ_KOKYAKU_SAISIN_FILEPATH2	=	KOKYAKU_SAISIN_FILEPATH2
		,@WNJ_KOKYAKU_SAISYU_HANTEI_KB	=	KOKYAKU_SAISYU_HANTEI_KB
		,@WNJ_KOKYAKU_SAISYU_HANTEI_NAME	=	KOKYAKU_SAISYU_HANTEI_NAME
		,@WNJ_KOKYAKU_SAISYU_HANTEI_YMD	=	KOKYAKU_SAISYU_HANTEI_YMD
		,@WNJ_SAIKAKO_SIJI_FG	=	SAIKAKO_SIJI_FG
		,@WNJ_HAIKYAKU_YMD	=	HAIKYAKU_YMD
		,@WNJ_HAIKYAKU_KB	=	HAIKYAKU_KB
		,@WNJ_HAIKYAKU_KB_NAME	=	HAIKYAKU_KB_NAME
		,@WNJ_HAIKYAKU_HOUHOU	=	HAIKYAKU_HOUHOU
		,@WNJ_HAIKYAKU_TANTO_ID	=	HAIKYAKU_TANTO_ID
		,@WNJ_HAIKYAKU_TANTO_NAME	=	HAIKYAKU_TANTO_NAME
		,@WNJ_SAIKAKO_SIJI_NO	=	SAIKAKO_SIJI_NO
		,@WNJ_SAIKAKO_SAGYO_KAN_YMD	=	SAIKAKO_SAGYO_KAN_YMD
		,@WNJ_SAIKAKO_KENSA_YMD	=	SAIKAKO_KENSA_YMD
		,@WNJ_KENSA_KEKKA_KB	=	KENSA_KEKKA_KB
		,@WNJ_KENSA_KEKKA_NAME	=	KENSA_KEKKA_NAME
		,@WNJ_SEIGI_TANTO_ID	=	SEIGI_TANTO_ID
		,@WNJ_SEIGI_TANTO_NAME	=	SEIGI_TANTO_NAME
		,@WNJ_SEIZO_TANTO_ID	=	SEIZO_TANTO_ID
		,@WNJ_SEIZO_TANTO_NAME	=	SEIZO_TANTO_NAME
		,@WNJ_KENSA_TANTO_ID	=	KENSA_TANTO_ID
		,@WNJ_KENSA_TANTO_NAME	=	KENSA_TANTO_NAME
		,@WNJ_HENKYAKU_YMD	=	HENKYAKU_YMD
		,@WNJ_HENKYAKU_SAKI	=	HENKYAKU_SAKI
		,@WNJ_HENKYAKU_TANTO_ID	=	HENKYAKU_TANTO_ID
		,@WNJ_HENKYAKU_TANTO_NAME	=	HENKYAKU_TANTO_NAME
		,@WNJ_HENKYAKU_BIKO	=	HENKYAKU_BIKO
		,@WNJ_TENYO_KISYU_ID	=	TENYO_KISYU_ID
		--,@WNJ_TENYO_KISYU	=	TENYO_KISYU
		,@WNJ_TENYO_KISYU_NAME	=	TENYO_KISYU_NAME
		,@WNJ_TENYO_BUHIN_BANGO	=	TENYO_BUHIN_BANGO
		,@WNJ_TENYO_GOKI	=	TENYO_GOKI
		,@WNJ_TENYO_LOT	=	TENYO_LOT
		,@WNJ_TENYO_YMD	=	TENYO_YMD
		,@WNJ_SYOCHI_KEKKA_A	=	SYOCHI_KEKKA_A
		,@WNJ_SYOCHI_KEKKA_A_NAME	=	SYOCHI_KEKKA_A_NAME
		,@WNJ_SYOCHI_KEKKA_B	=	SYOCHI_KEKKA_B
		,@WNJ_SYOCHI_KEKKA_B_NAME	=	SYOCHI_KEKKA_B_NAME
		,@WNJ_SYOCHI_KEKKA_C	=	SYOCHI_KEKKA_C
		,@WNJ_SYOCHI_KEKKA_C_NAME	=	SYOCHI_KEKKA_C_NAME
		,@WNJ_SYOCHI_D_UMU_KB	=	SYOCHI_D_UMU_KB
		,@WNJ_SYOCHI_D_UMU_NAME	=	SYOCHI_D_UMU_NAME
		,@WNJ_SYOCHI_D_YOHI_KB	=	SYOCHI_D_YOHI_KB
		,@WNJ_SYOCHI_D_YOHI_NAME	=	SYOCHI_D_YOHI_NAME
		,@WNJ_SYOCHI_D_SYOCHI_KIROKU	=	SYOCHI_D_SYOCHI_KIROKU
		,@WNJ_SYOCHI_E_UMU_KB	=	SYOCHI_E_UMU_KB
		,@WNJ_SYOCHI_E_UMU_NAME	=	SYOCHI_E_UMU_NAME
		,@WNJ_SYOCHI_E_YOHI_KB	=	SYOCHI_E_YOHI_KB
		,@WNJ_SYOCHI_E_YOHI_NAME	=	SYOCHI_E_YOHI_NAME
		,@WNJ_SYOCHI_E_SYOCHI_KIROKU	=	SYOCHI_E_SYOCHI_KIROKU
		,@WNJ_FILE_PATH	=	FILE_PATH
		,@WNJ_G_FILE_PATH1	=	G_FILE_PATH1
		,@WNJ_G_FILE_PATH2	=	G_FILE_PATH2
		,@WNJ_HASSEI_KOTEI_GL_SYAIN_ID	=	HASSEI_KOTEI_GL_SYAIN_ID
		,@WNJ_HASSEI_KOTEI_GL_SYAIN_NAME	=	HASSEI_KOTEI_GL_SYAIN_NAME
		FROM V008_NCR_R		
		WHERE 
			HOKOKU_NO = @HOKOKUSYO_NO
				AND SASIMODOSI_YMDHNS = (SELECT MAX(WK.SASIMODOSI_YMDHNS) FROM V008_NCR_R WK WHERE WK.HOKOKU_NO = @HOKOKUSYO_NO AND WK.SASIMODOSI_YMDHNS < @SASIMODOSI_YMDHNS);
			    
		
		 SELECT 
		 @WNR_HOKOKU_NO	=	HOKOKU_NO
		,@WNR_BUMON_KB	=	BUMON_KB
		,@WNR_BUMON_NAME	=	BUMON_NAME
		,@WNR_CLOSE_FG	=	CLOSE_FG
		,@WNR_KISYU_ID	=	KISYU_ID
		--,@WNR_KISYU	=	KISYU
		,@WNR_KISYU_NAME	=	KISYU_NAME
		,@WNR_SYANAI_CD	=	SYANAI_CD
		,@WNR_BUHIN_BANGO	=	BUHIN_BANGO
		,@WNR_BUHIN_NAME	=	BUHIN_NAME
		,@WNR_GOKI	=	GOKI
		,@WNR_SURYO	=	SURYO
		,@WNR_SAIHATU	=	SAIHATU
		,@WNR_FUTEKIGO_JYOTAI_KB	=	FUTEKIGO_JYOTAI_KB
		,@WNR_FUTEKIGO_JYOTAI_NAME	=	FUTEKIGO_JYOTAI_NAME
		,@WNR_FUTEKIGO_NAIYO	=	FUTEKIGO_NAIYO
		,@WNR_FUTEKIGO_KB	=	FUTEKIGO_KB
		,@WNR_FUTEKIGO_NAME	=	FUTEKIGO_NAME
		,@WNR_FUTEKIGO_S_KB	=	FUTEKIGO_S_KB
		,@WNR_FUTEKIGO_S_NAME	=	FUTEKIGO_S_NAME
		,@WNR_ZUMEN_KIKAKU	=	ZUMEN_KIKAKU
		,@WNR_YOKYU_NAIYO	=	YOKYU_NAIYO
		,@WNR_KANSATU_KEKKA	=	KANSATU_KEKKA
		,@WNR_ZESEI_SYOCHI_YOHI_KB	=	ZESEI_SYOCHI_YOHI_KB
		,@WNR_ZESEI_SYOCHI_YOHI_NAME	=	ZESEI_SYOCHI_YOHI_NAME
		,@WNR_ZESEI_NASI_RIYU	=	ZESEI_NASI_RIYU
		,@WNR_JIZEN_SINSA_HANTEI_KB	=	JIZEN_SINSA_HANTEI_KB
		,@WNR_JIZEN_SINSA_HANTEI_NAME	=	JIZEN_SINSA_HANTEI_NAME
		,@WNR_JIZEN_SINSA_SYAIN_ID	=	JIZEN_SINSA_SYAIN_ID
		,@WNR_JIZEN_SINSA_SYAIN_NAME	=	JIZEN_SINSA_SYAIN_NAME
		,@WNR_JIZEN_SINSA_YMD	=	JIZEN_SINSA_YMD
		,@WNR_SAISIN_KAKUNIN_SYAIN_ID	=	SAISIN_KAKUNIN_SYAIN_ID
		,@WNR_SAISIN_KAKUNIN_SYAIN_NAME	=	SAISIN_KAKUNIN_SYAIN_NAME
		,@WNR_SAISIN_KAKUNIN_YMD	=	SAISIN_KAKUNIN_YMD
		,@WNR_SAISIN_IINKAI_HANTEI_KB	=	SAISIN_IINKAI_HANTEI_KB
		,@WNR_SAISIN_IINKAI_HANTEI_NAME	=	SAISIN_IINKAI_HANTEI_NAME
		,@WNR_SAISIN_GIJYUTU_SYAIN_ID	=	SAISIN_GIJYUTU_SYAIN_ID
		,@WNR_SAISIN_GIJYUTU_SYAIN_NAME	=	SAISIN_GIJYUTU_SYAIN_NAME
		,@WNR_SAISIN_GIJYUTU_YMD	=	SAISIN_GIJYUTU_YMD
		,@WNR_SAISIN_HINSYO_SYAIN_ID	=	SAISIN_HINSYO_SYAIN_ID
		,@WNR_SAISIN_HINSYO_SYAIN_NAME	=	SAISIN_HINSYO_SYAIN_NAME
		,@WNR_SAISIN_HINSYO_YMD	=	SAISIN_HINSYO_YMD
		,@WNR_SAISIN_IINKAI_SIRYO_NO	=	SAISIN_IINKAI_SIRYO_NO
		,@WNR_ITAG_NO	=	ITAG_NO
		,@WNR_KOKYAKU_SAISIN_TANTO_ID	=	KOKYAKU_SAISIN_TANTO_ID
		,@WNR_KOKYAKU_SAISIN_TANTO_NAME	=	KOKYAKU_SAISIN_TANTO_NAME
		,@WNR_KOKYAKU_SAISIN_YMD	=	KOKYAKU_SAISIN_YMD
		,@WNR_KOKYAKU_SAISIN_FILEPATH1	=	KOKYAKU_SAISIN_FILEPATH1
		,@WNR_KOKYAKU_SAISIN_FILEPATH2	=	KOKYAKU_SAISIN_FILEPATH2
		,@WNR_KOKYAKU_HANTEI_SIJI_KB	=	KOKYAKU_HANTEI_SIJI_KB
		,@WNR_KOKYAKU_HANTEI_SIJI_NAME	=	KOKYAKU_HANTEI_SIJI_NAME
		,@WNR_KOKYAKU_HANTEI_SIJI_YMD	=	KOKYAKU_HANTEI_SIJI_YMD
		,@WNR_KOKYAKU_SAISYU_HANTEI_KB	=	KOKYAKU_SAISYU_HANTEI_KB
		,@WNR_KOKYAKU_SAISYU_HANTEI_NAME	=	KOKYAKU_SAISYU_HANTEI_NAME
		,@WNR_KOKYAKU_SAISYU_HANTEI_YMD	=	KOKYAKU_SAISYU_HANTEI_YMD
		,@WNR_SAIKAKO_SIJI_FG	=	SAIKAKO_SIJI_FG
		,@WNR_HAIKYAKU_YMD	=	HAIKYAKU_YMD
		,@WNR_HAIKYAKU_KB	=	HAIKYAKU_KB
		,@WNR_HAIKYAKU_KB_NAME	=	HAIKYAKU_KB_NAME
		,@WNR_HAIKYAKU_HOUHOU	=	HAIKYAKU_HOUHOU
		,@WNR_HAIKYAKU_TANTO_ID	=	HAIKYAKU_TANTO_ID
		,@WNR_HAIKYAKU_TANTO_NAME	=	HAIKYAKU_TANTO_NAME
		,@WNR_SAIKAKO_SIJI_NO	=	SAIKAKO_SIJI_NO
		,@WNR_SAIKAKO_SAGYO_KAN_YMD	=	SAIKAKO_SAGYO_KAN_YMD
		,@WNR_SAIKAKO_KENSA_YMD	=	SAIKAKO_KENSA_YMD
		,@WNR_KENSA_KEKKA_KB	=	KENSA_KEKKA_KB
		,@WNR_KENSA_KEKKA_NAME	=	KENSA_KEKKA_NAME
		,@WNR_SEIGI_TANTO_ID	=	SEIGI_TANTO_ID
		,@WNR_SEIGI_TANTO_NAME	=	SEIGI_TANTO_NAME
		,@WNR_SEIZO_TANTO_ID	=	SEIZO_TANTO_ID
		,@WNR_SEIZO_TANTO_NAME	=	SEIZO_TANTO_NAME
		,@WNR_KENSA_TANTO_ID	=	KENSA_TANTO_ID
		,@WNR_KENSA_TANTO_NAME	=	KENSA_TANTO_NAME
		,@WNR_HENKYAKU_YMD	=	HENKYAKU_YMD
		,@WNR_HENKYAKU_SAKI	=	HENKYAKU_SAKI
		,@WNR_HENKYAKU_TANTO_ID	=	HENKYAKU_TANTO_ID
		,@WNR_HENKYAKU_TANTO_NAME	=	HENKYAKU_TANTO_NAME
		,@WNR_HENKYAKU_BIKO	=	HENKYAKU_BIKO
		,@WNR_TENYO_KISYU_ID	=	TENYO_KISYU_ID
		--,@WNR_TENYO_KISYU	=	TENYO_KISYU
		,@WNR_TENYO_KISYU_NAME	=	TENYO_KISYU_NAME
		,@WNR_TENYO_BUHIN_BANGO	=	TENYO_BUHIN_BANGO
		,@WNR_TENYO_GOKI	=	TENYO_GOKI
		,@WNR_TENYO_LOT	=	TENYO_LOT
		,@WNR_TENYO_YMD	=	TENYO_YMD
		,@WNR_SYOCHI_KEKKA_A	=	SYOCHI_KEKKA_A
		,@WNR_SYOCHI_KEKKA_A_NAME	=	SYOCHI_KEKKA_A_NAME
		,@WNR_SYOCHI_KEKKA_B	=	SYOCHI_KEKKA_B
		,@WNR_SYOCHI_KEKKA_B_NAME	=	SYOCHI_KEKKA_B_NAME
		,@WNR_SYOCHI_KEKKA_C	=	SYOCHI_KEKKA_C
		,@WNR_SYOCHI_KEKKA_C_NAME	=	SYOCHI_KEKKA_C_NAME
		,@WNR_SYOCHI_D_UMU_KB	=	SYOCHI_D_UMU_KB
		,@WNR_SYOCHI_D_UMU_NAME	=	SYOCHI_D_UMU_NAME
		,@WNR_SYOCHI_D_YOHI_KB	=	SYOCHI_D_YOHI_KB
		,@WNR_SYOCHI_D_YOHI_NAME	=	SYOCHI_D_YOHI_NAME
		,@WNR_SYOCHI_D_SYOCHI_KIROKU	=	SYOCHI_D_SYOCHI_KIROKU
		,@WNR_SYOCHI_E_UMU_KB	=	SYOCHI_E_UMU_KB
		,@WNR_SYOCHI_E_UMU_NAME	=	SYOCHI_E_UMU_NAME
		,@WNR_SYOCHI_E_YOHI_KB	=	SYOCHI_E_YOHI_KB
		,@WNR_SYOCHI_E_YOHI_NAME	=	SYOCHI_E_YOHI_NAME
		,@WNR_SYOCHI_E_SYOCHI_KIROKU	=	SYOCHI_E_SYOCHI_KIROKU
		,@WNR_FILE_PATH	=	FILE_PATH
		,@WNR_G_FILE_PATH1	=	G_FILE_PATH1
		,@WNR_G_FILE_PATH2	=	G_FILE_PATH2
		,@WNR_HASSEI_KOTEI_GL_SYAIN_ID	=	HASSEI_KOTEI_GL_SYAIN_ID
		,@WNR_HASSEI_KOTEI_GL_SYAIN_NAME	=	HASSEI_KOTEI_GL_SYAIN_NAME
		FROM V008_NCR_R
		WHERE 
			HOKOKU_NO = @HOKOKUSYO_NO
		AND SASIMODOSI_YMDHNS = @SASIMODOSI_YMDHNS;

		--初期値以外からの変更のみ変更処置とみなす

		--機種
		IF @WNJ_KISYU_ID <>	@WNR_KISYU_ID AND @WNJ_KISYU_ID<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'機種'
			,@WNR_KISYU_NAME
			,@WNJ_KISYU_NAME
			);
		--社内コード
		IF @WNJ_SYANAI_CD <> @WNR_SYANAI_CD AND RTRIM(@WNJ_SYANAI_CD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'社内コード'
			,@WNR_SYANAI_CD
			,@WNJ_SYANAI_CD
			);
		--部品番号
		IF @WNJ_BUHIN_BANGO <> @WNR_BUHIN_BANGO AND RTRIM(@WNJ_BUHIN_BANGO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'部品番号'
			,@WNR_SYANAI_CD
			,@WNJ_SYANAI_CD
			);
		--部品名称
		IF @WNJ_BUHIN_NAME <> @WNR_BUHIN_NAME AND RTRIM(@WNJ_BUHIN_NAME)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'部品名称'
			,@WNR_BUHIN_NAME
			,@WNJ_BUHIN_NAME
			);		
		--号機
		IF @WNJ_GOKI <> @WNR_GOKI AND RTRIM(@WNJ_GOKI)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'号機'
			,@WNR_GOKI
			,@WNJ_GOKI
			);
		--数量
		IF @WNJ_SURYO <> @WNR_SURYO AND @WNJ_SURYO<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'数量'
			,@WNR_SURYO
			,@WNJ_SURYO
			);
		--再発
		IF @WNJ_SAIHATU <> @WNR_SAIHATU AND RTRIM(@WNJ_SAIHATU)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再発'
			,@WNR_SAIHATU
			,@WNJ_SAIHATU
			);
		--不適合状態区分
		IF @WNJ_FUTEKIGO_JYOTAI_KB <> @WNR_FUTEKIGO_JYOTAI_KB AND RTRIM(@WNJ_FUTEKIGO_JYOTAI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'不適合状態区分'
			,@WNR_FUTEKIGO_JYOTAI_NAME
			,@WNJ_FUTEKIGO_JYOTAI_NAME
			);
		--不適合状態内容
		IF @WNJ_FUTEKIGO_NAIYO <> @WNR_FUTEKIGO_NAIYO AND RTRIM(@WNJ_FUTEKIGO_NAIYO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'不適合状態内容'
			,@WNR_FUTEKIGO_NAIYO
			,@WNJ_FUTEKIGO_NAIYO
			);
		--不適合区分
		IF @WNJ_FUTEKIGO_KB <> @WNR_FUTEKIGO_KB AND RTRIM(@WNJ_FUTEKIGO_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'不適合区分'
			,@WNR_FUTEKIGO_NAME
			,@WNJ_FUTEKIGO_NAME
			);	
		--不適合詳細区分
		IF @WNJ_FUTEKIGO_S_KB <> @WNR_FUTEKIGO_S_KB AND RTRIM(@WNJ_FUTEKIGO_S_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'不適合詳細区分'
			,@WNR_FUTEKIGO_S_NAME
			,@WNJ_FUTEKIGO_S_NAME
			);	
		--図面規格
		IF @WNJ_ZUMEN_KIKAKU <> @WNR_ZUMEN_KIKAKU AND RTRIM(@WNJ_ZUMEN_KIKAKU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'図面規格'
			,@WNR_ZUMEN_KIKAKU
			,@WNJ_ZUMEN_KIKAKU
			);	
		--要求内容
		IF @WNJ_YOKYU_NAIYO <> @WNR_YOKYU_NAIYO AND RTRIM(@WNJ_YOKYU_NAIYO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'要求内容'
			,@WNR_YOKYU_NAIYO
			,@WNJ_YOKYU_NAIYO
			);	
		--観察結果
		IF @WNJ_KANSATU_KEKKA <> @WNR_KANSATU_KEKKA AND RTRIM(@WNJ_KANSATU_KEKKA)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'観察結果'
			,@WNR_KANSATU_KEKKA
			,@WNJ_KANSATU_KEKKA
			);	
		--是正処置要否区分
		IF @WNJ_ZESEI_SYOCHI_YOHI_KB <> @WNR_ZESEI_SYOCHI_YOHI_KB AND RTRIM(@WNJ_ZESEI_SYOCHI_YOHI_KB)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'是正処置要否区分'
			,@WNR_ZESEI_SYOCHI_YOHI_NAME
			,@WNJ_ZESEI_SYOCHI_YOHI_NAME
			);	
		--是正処置無理由
		IF @WNJ_ZESEI_NASI_RIYU <> @WNR_ZESEI_NASI_RIYU AND RTRIM(@WNJ_ZESEI_NASI_RIYU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'是正処置無理由'
			,@WNR_ZESEI_NASI_RIYU
			,@WNJ_ZESEI_NASI_RIYU
			);	
		--事前審査判定区分
		IF @WNJ_JIZEN_SINSA_HANTEI_KB <> @WNR_JIZEN_SINSA_HANTEI_KB AND RTRIM(@WNJ_JIZEN_SINSA_HANTEI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'事前審査判定区分'
			,@WNR_JIZEN_SINSA_HANTEI_NAME
			,@WNJ_JIZEN_SINSA_HANTEI_NAME
			);	
		--事前審査社員ID
		IF @WNJ_JIZEN_SINSA_SYAIN_NAME <> @WNR_JIZEN_SINSA_SYAIN_NAME AND RTRIM(@WNJ_JIZEN_SINSA_SYAIN_NAME)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'事前審査社員'
			,@WNR_JIZEN_SINSA_SYAIN_NAME
			,@WNJ_JIZEN_SINSA_SYAIN_NAME
			);	
		--事前審査日
		IF @WNJ_JIZEN_SINSA_YMD <> @WNR_JIZEN_SINSA_YMD AND RTRIM(@WNJ_JIZEN_SINSA_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'事前審査日'
			,@WNR_JIZEN_SINSA_YMD
			,@WNJ_JIZEN_SINSA_YMD
			);	
		--再審委員確認社員ID
		IF @WNJ_SAISIN_KAKUNIN_SYAIN_ID <> @WNR_SAISIN_KAKUNIN_SYAIN_ID AND RTRIM(@WNJ_SAISIN_KAKUNIN_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員確認社員'
			,@WNR_SAISIN_KAKUNIN_SYAIN_NAME
			,@WNJ_SAISIN_KAKUNIN_SYAIN_NAME
			);	
		--再審委員確認日
		IF @WNJ_SAISIN_KAKUNIN_YMD <> @WNR_SAISIN_KAKUNIN_YMD AND RTRIM(@WNJ_SAISIN_KAKUNIN_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員確認日'
			,@WNR_SAISIN_KAKUNIN_YMD
			,@WNJ_SAISIN_KAKUNIN_YMD
			);
		--再審委員会判定区分
		IF @WNJ_SAISIN_IINKAI_HANTEI_KB <> @WNR_SAISIN_IINKAI_HANTEI_KB AND RTRIM(@WNJ_SAISIN_IINKAI_HANTEI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員会判定区分'
			,@WNR_SAISIN_IINKAI_HANTEI_NAME
			,@WNJ_SAISIN_IINKAI_HANTEI_NAME
			);
		--再審委員技術社員ID
		IF @WNJ_SAISIN_GIJYUTU_SYAIN_ID <> @WNR_SAISIN_GIJYUTU_SYAIN_ID AND (@WNJ_SAISIN_GIJYUTU_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員技術社員'
			,@WNR_SAISIN_GIJYUTU_SYAIN_NAME
			,@WNJ_SAISIN_GIJYUTU_SYAIN_NAME
			);
		--再審委員技術確認日
		IF @WNJ_SAISIN_GIJYUTU_YMD <> @WNR_SAISIN_GIJYUTU_YMD AND RTRIM(@WNJ_SAISIN_GIJYUTU_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員技術確認日'
			,@WNR_SAISIN_GIJYUTU_YMD
			,@WNJ_SAISIN_GIJYUTU_YMD
			);
		--再審委員品証社員ID
		IF @WNJ_SAISIN_HINSYO_SYAIN_ID <> @WNR_SAISIN_HINSYO_SYAIN_ID AND (@WNJ_SAISIN_HINSYO_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員品証社員'
			,@WNR_SAISIN_HINSYO_SYAIN_NAME
			,@WNJ_SAISIN_HINSYO_SYAIN_NAME
			);
		--再審委員品証確認日
		IF @WNJ_SAISIN_HINSYO_YMD <> @WNR_SAISIN_HINSYO_YMD AND RTRIM(@WNJ_SAISIN_HINSYO_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員品証確認日'
			,@WNR_SAISIN_HINSYO_YMD
			,@WNJ_SAISIN_HINSYO_YMD
			);
		--再審委員会資料No
		IF @WNJ_SAISIN_IINKAI_SIRYO_NO <> @WNR_SAISIN_IINKAI_SIRYO_NO AND RTRIM(@WNJ_SAISIN_IINKAI_SIRYO_NO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再審委員会資料No'
			,@WNR_SAISIN_IINKAI_SIRYO_NO
			,@WNJ_SAISIN_IINKAI_SIRYO_NO
			);
		--ITAGNo
		IF @WNJ_ITAG_NO <> @WNR_ITAG_NO AND RTRIM(@WNJ_ITAG_NO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'ITAGNo'
			,@WNR_ITAG_NO
			,@WNJ_ITAG_NO
			);
		--顧客再審申請担当ID
		IF @WNJ_KOKYAKU_SAISIN_TANTO_ID <> @WNR_KOKYAKU_SAISIN_TANTO_ID AND (@WNJ_KOKYAKU_SAISIN_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客再審申請担当'
			,@WNR_KOKYAKU_SAISIN_TANTO_NAME
			,@WNJ_KOKYAKU_SAISIN_TANTO_NAME
			);
		--顧客再審申請日
		IF @WNJ_KOKYAKU_SAISIN_YMD <> @WNR_KOKYAKU_SAISIN_YMD AND RTRIM(@WNJ_KOKYAKU_SAISIN_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客再審申請日'
			,@WNR_KOKYAKU_SAISIN_YMD
			,@WNJ_KOKYAKU_SAISIN_YMD
			);
		--顧客再審申請資料1
		IF @WNJ_KOKYAKU_SAISIN_FILEPATH1 <> @WNR_KOKYAKU_SAISIN_FILEPATH1
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客再審申請添付資料1'
			,@WNR_KOKYAKU_SAISIN_FILEPATH1
			,@WNJ_KOKYAKU_SAISIN_FILEPATH1
			);
		--顧客再審申請資料2
		IF @WNJ_KOKYAKU_SAISIN_FILEPATH2 <> @WNR_KOKYAKU_SAISIN_FILEPATH2
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客再審申請添付資料2'
			,@WNR_KOKYAKU_SAISIN_FILEPATH2
			,@WNJ_KOKYAKU_SAISIN_FILEPATH2
			);
		--顧客判定指示区分
		IF @WNJ_KOKYAKU_HANTEI_SIJI_KB <> @WNR_KOKYAKU_HANTEI_SIJI_KB AND RTRIM(@WNJ_KOKYAKU_HANTEI_SIJI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客判定指示区分'
			,@WNR_KOKYAKU_HANTEI_SIJI_NAME
			,@WNJ_KOKYAKU_HANTEI_SIJI_NAME
			);
		--顧客判定指示日
		IF @WNJ_KOKYAKU_HANTEI_SIJI_YMD <> @WNR_KOKYAKU_HANTEI_SIJI_YMD AND RTRIM(@WNJ_KOKYAKU_HANTEI_SIJI_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客判定指示日'
			,@WNR_KOKYAKU_HANTEI_SIJI_YMD
			,@WNJ_KOKYAKU_HANTEI_SIJI_YMD
			);
		--顧客最終判定区分
		IF @WNJ_KOKYAKU_SAISYU_HANTEI_KB <> @WNR_KOKYAKU_SAISYU_HANTEI_KB AND RTRIM(@WNJ_KOKYAKU_SAISYU_HANTEI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客最終判定区分'
			,@WNR_KOKYAKU_SAISYU_HANTEI_NAME
			,@WNJ_KOKYAKU_SAISYU_HANTEI_NAME
			);
		--顧客最終判定日
		IF @WNJ_KOKYAKU_SAISYU_HANTEI_YMD <> @WNR_KOKYAKU_SAISYU_HANTEI_YMD AND RTRIM(@WNJ_KOKYAKU_SAISYU_HANTEI_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'顧客最終判定日'
			,@WNR_KOKYAKU_SAISYU_HANTEI_YMD
			,@WNJ_KOKYAKU_SAISYU_HANTEI_YMD
			);
		--再加工指示フラグ
		IF @WNJ_SAIKAKO_SIJI_FG <> @WNR_SAIKAKO_SIJI_FG AND RTRIM(@WNJ_SAIKAKO_SIJI_FG)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再加工指示フラグ'
			,@WNR_SAIKAKO_SIJI_FG
			,@WNJ_SAIKAKO_SIJI_FG
			);
		--廃却年月日
		IF @WNJ_HAIKYAKU_YMD <> @WNR_HAIKYAKU_YMD AND RTRIM(@WNJ_HAIKYAKU_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'廃却年月日'
			,@WNR_HAIKYAKU_YMD
			,@WNJ_HAIKYAKU_YMD
			);
		--廃却方法区分
		IF @WNJ_HAIKYAKU_KB <> @WNR_HAIKYAKU_KB AND RTRIM(@WNJ_HAIKYAKU_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'廃却方法区分'
			,@WNR_HAIKYAKU_KB_NAME
			,@WNJ_HAIKYAKU_KB_NAME
			);
		--廃却方法内容
		IF @WNJ_HAIKYAKU_HOUHOU <> @WNR_HAIKYAKU_HOUHOU AND RTRIM(@WNJ_HAIKYAKU_HOUHOU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'廃却方法内容'
			,@WNR_HAIKYAKU_HOUHOU
			,@WNJ_HAIKYAKU_HOUHOU
			);
		--廃却実施者ID
		IF @WNJ_HAIKYAKU_TANTO_ID <> @WNR_HAIKYAKU_TANTO_ID AND (@WNJ_HAIKYAKU_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'廃却実施者'
			,@WNR_HAIKYAKU_TANTO_NAME
			,@WNJ_HAIKYAKU_TANTO_NAME
			);
		--再加工指示文書No
		IF @WNJ_SAIKAKO_SIJI_NO <> @WNR_SAIKAKO_SIJI_NO AND RTRIM(@WNJ_SAIKAKO_SIJI_NO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再加工指示文書No'
			,@WNR_SAIKAKO_SIJI_NO
			,@WNJ_SAIKAKO_SIJI_NO
			);
		--再加工作業完了日
		IF @WNJ_SAIKAKO_SAGYO_KAN_YMD <> @WNR_SAIKAKO_SAGYO_KAN_YMD AND RTRIM(@WNJ_SAIKAKO_SAGYO_KAN_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再加工作業完了日'
			,@WNR_SAIKAKO_SAGYO_KAN_YMD
			,@WNJ_SAIKAKO_SAGYO_KAN_YMD
			);
		--再加工検査年月日
		IF @WNJ_SAIKAKO_KENSA_YMD <> @WNR_SAIKAKO_KENSA_YMD AND RTRIM(@WNJ_SAIKAKO_KENSA_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'再加工検査年月日'
			,@WNR_SAIKAKO_KENSA_YMD
			,@WNJ_SAIKAKO_KENSA_YMD
			);
		--検査結果区分
		IF @WNJ_KENSA_KEKKA_KB <> @WNR_KENSA_KEKKA_KB AND RTRIM(@WNJ_KENSA_KEKKA_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'検査結果区分'
			,@WNR_KENSA_KEKKA_NAME
			,@WNJ_KENSA_KEKKA_NAME
			);
		--生技社員ID
		IF @WNJ_SEIGI_TANTO_ID <> @WNR_SEIGI_TANTO_ID AND (@WNJ_SEIGI_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'生技社員'
			,@WNR_SEIGI_TANTO_NAME
			,@WNJ_SEIGI_TANTO_NAME
			);
		--製造社員ID
		IF @WNJ_SEIZO_TANTO_ID <> @WNR_SEIZO_TANTO_ID AND (@WNJ_SEIZO_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'製造社員'
			,@WNR_SEIZO_TANTO_NAME
			,@WNJ_SEIZO_TANTO_NAME
			);
		--検査社員ID
		IF @WNJ_KENSA_TANTO_ID <> @WNR_KENSA_TANTO_ID AND (@WNJ_KENSA_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'検査社員'
			,@WNR_KENSA_TANTO_NAME
			,@WNJ_KENSA_TANTO_NAME
			);
		--返却年月日
		IF @WNJ_HENKYAKU_YMD <> @WNR_HENKYAKU_YMD AND RTRIM(@WNJ_HENKYAKU_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'返却年月日'
			,@WNR_HENKYAKU_YMD
			,@WNJ_HENKYAKU_YMD
			);
		--返却先
		IF @WNJ_HENKYAKU_SAKI <> @WNR_HENKYAKU_SAKI AND RTRIM(@WNJ_HENKYAKU_SAKI)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'返却先'
			,@WNR_HENKYAKU_SAKI
			,@WNJ_HENKYAKU_SAKI
			);
		--返却実施者ID
		IF @WNJ_HENKYAKU_TANTO_ID <> @WNR_HENKYAKU_TANTO_ID AND (@WNJ_HENKYAKU_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'返却実施者'
			,@WNR_HENKYAKU_TANTO_NAME
			,@WNJ_HENKYAKU_TANTO_NAME
			);
		--返却実施備考
		IF @WNJ_HENKYAKU_BIKO <> @WNR_HENKYAKU_BIKO AND RTRIM(@WNJ_HENKYAKU_BIKO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'返却実施備考'
			,@WNR_HENKYAKU_BIKO
			,@WNJ_HENKYAKU_BIKO
			);
		--転用先機種ID
		IF @WNJ_TENYO_KISYU_ID <> @WNR_TENYO_KISYU_ID AND (@WNJ_TENYO_KISYU_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'転用先機種'
			,@WNR_TENYO_KISYU_NAME
			,@WNJ_TENYO_KISYU_NAME
			);
		--転用先部品番号
		IF @WNJ_TENYO_BUHIN_BANGO <> @WNR_TENYO_BUHIN_BANGO AND RTRIM(@WNJ_TENYO_BUHIN_BANGO)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'転用先部品番号'
			,@WNR_TENYO_BUHIN_BANGO
			,@WNJ_TENYO_BUHIN_BANGO
			);
		--転用先号機
		IF @WNJ_TENYO_GOKI <> @WNR_TENYO_GOKI AND RTRIM(@WNJ_TENYO_GOKI)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'転用先号機'
			,@WNR_TENYO_GOKI
			,@WNJ_TENYO_GOKI
			);
		--転用先LOT
		IF @WNJ_TENYO_LOT <> @WNR_TENYO_LOT AND (@WNJ_TENYO_LOT)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'転用先LOT'
			,@WNR_TENYO_LOT
			,@WNJ_TENYO_LOT
			);
		--転用年月日
		IF @WNJ_TENYO_YMD <> @WNR_TENYO_YMD AND RTRIM(@WNJ_TENYO_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'転用先LOT'
			,@WNR_TENYO_YMD
			,@WNJ_TENYO_YMD
			);
		--処置結果a
		IF @WNJ_SYOCHI_KEKKA_A <> @WNR_SYOCHI_KEKKA_A AND RTRIM(@WNJ_SYOCHI_KEKKA_A)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置結果a'
			,@WNR_SYOCHI_KEKKA_A_NAME
			,@WNJ_SYOCHI_KEKKA_A_NAME
			);
		--処置結果b
		IF @WNJ_SYOCHI_KEKKA_B <> @WNR_SYOCHI_KEKKA_B AND RTRIM(@WNJ_SYOCHI_KEKKA_B)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置結果b'
			,@WNR_SYOCHI_KEKKA_B_NAME
			,@WNJ_SYOCHI_KEKKA_B_NAME
			);
		--処置結果C
		IF @WNJ_SYOCHI_KEKKA_C <> @WNR_SYOCHI_KEKKA_C AND RTRIM(@WNJ_SYOCHI_KEKKA_C)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置結果c'
			,@WNR_SYOCHI_KEKKA_C_NAME
			,@WNJ_SYOCHI_KEKKA_C_NAME
			);
		--処置d有無区分
		IF @WNJ_SYOCHI_D_UMU_KB <> @WNR_SYOCHI_D_UMU_KB AND RTRIM(@WNJ_SYOCHI_D_UMU_KB)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置d有無区分'
			,@WNR_SYOCHI_D_UMU_NAME
			,@WNJ_SYOCHI_D_UMU_NAME
			);
		--処置d要否区分
		IF @WNJ_SYOCHI_D_YOHI_KB <> @WNR_SYOCHI_D_YOHI_KB AND RTRIM(@WNJ_SYOCHI_D_YOHI_KB)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置d要否区分'
			,@WNR_SYOCHI_D_YOHI_NAME
			,@WNJ_SYOCHI_D_YOHI_NAME
			);
		--処置d処置記録
		IF @WNJ_SYOCHI_D_SYOCHI_KIROKU <> @WNR_SYOCHI_D_SYOCHI_KIROKU AND RTRIM(@WNJ_SYOCHI_D_SYOCHI_KIROKU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置d処置記録'
			,@WNR_SYOCHI_D_SYOCHI_KIROKU
			,@WNJ_SYOCHI_D_SYOCHI_KIROKU
			);
		--処置e有無区分
		IF @WNJ_SYOCHI_E_UMU_KB <> @WNR_SYOCHI_E_UMU_KB AND RTRIM(@WNJ_SYOCHI_E_UMU_KB)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置e有無区分'
			,@WNR_SYOCHI_E_UMU_NAME
			,@WNJ_SYOCHI_E_UMU_NAME
			);
		--処置e要否区分
		IF @WNJ_SYOCHI_E_YOHI_KB <> @WNR_SYOCHI_E_YOHI_KB AND RTRIM(@WNJ_SYOCHI_E_YOHI_KB)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置e要否区分'
			,@WNR_SYOCHI_E_YOHI_NAME
			,@WNJ_SYOCHI_E_YOHI_NAME
			);
		--処置e処置記録
		IF @WNJ_SYOCHI_E_SYOCHI_KIROKU <> @WNR_SYOCHI_E_SYOCHI_KIROKU AND RTRIM(@WNJ_SYOCHI_E_SYOCHI_KIROKU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'処置e処置記録'
			,@WNR_SYOCHI_E_SYOCHI_KIROKU
			,@WNJ_SYOCHI_E_SYOCHI_KIROKU
			);
		--ファイルパス
		IF @WNJ_FILE_PATH <> @WNR_FILE_PATH AND RTRIM(@WNJ_FILE_PATH)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'ファイルパス'
			,@WNR_FILE_PATH
			,@WNJ_FILE_PATH
			);
		--画像ファイルパス1
		IF @WNJ_G_FILE_PATH1 <> @WNR_G_FILE_PATH1 AND RTRIM(@WNJ_G_FILE_PATH1)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'画像ファイルパス1'
			,@WNR_G_FILE_PATH1
			,@WNJ_G_FILE_PATH1
			);
		--画像ファイルパス2
		IF @WNJ_G_FILE_PATH2 <> @WNR_G_FILE_PATH2 AND RTRIM(@WNJ_G_FILE_PATH2)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'画像ファイルパス2'
			,@WNR_G_FILE_PATH2
			,@WNJ_G_FILE_PATH2
			);
		--CAR 発生工程ＧＬ担当
		IF @WNJ_HASSEI_KOTEI_GL_SYAIN_ID <> @WNR_HASSEI_KOTEI_GL_SYAIN_ID AND RTRIM(@WNJ_HASSEI_KOTEI_GL_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'発生工程GL担当者'
			,@WNR_HASSEI_KOTEI_GL_SYAIN_NAME
			,@WNJ_HASSEI_KOTEI_GL_SYAIN_NAME
			);

	END
	--CAR
	ELSE
	BEGIN
		SELECT 
		 @WCJ_HOKOKU_NO= 	HOKOKU_NO	--
		,@WCJ_BUMON_KB= 	BUMON_KB	--
		,@WCJ_BUMON_NAME= 	BUMON_NAME	--
		,@WCJ_CLOSE_FG= 	CLOSE_FG	--
		,@WCJ_SETUMON_1= 	SETUMON_1	--
		,@WCJ_KAITO_1= 	KAITO_1	--
		,@WCJ_SETUMON_2= 	SETUMON_2	--
		,@WCJ_KAITO_2= 	KAITO_2	--
		,@WCJ_SETUMON_3= 	SETUMON_3	--
		,@WCJ_KAITO_3= 	KAITO_3	--
		,@WCJ_SETUMON_4= 	SETUMON_4	--
		,@WCJ_KAITO_4= 	KAITO_4	--
		,@WCJ_SETUMON_5= 	SETUMON_5	--
		,@WCJ_KAITO_5= 	KAITO_5	--
		,@WCJ_SETUMON_6= 	SETUMON_6	--
		,@WCJ_KAITO_6= 	KAITO_6	--
		,@WCJ_SETUMON_7= 	SETUMON_7	--
		,@WCJ_KAITO_7= 	KAITO_7	--
		,@WCJ_SETUMON_8= 	SETUMON_8	--
		,@WCJ_KAITO_8= 	KAITO_8	--
		,@WCJ_SETUMON_9= 	SETUMON_9	--
		,@WCJ_KAITO_9= 	KAITO_9	--
		,@WCJ_SETUMON_10= 	SETUMON_10	--
		,@WCJ_KAITO_10= 	KAITO_10	--
		,@WCJ_SETUMON_11= 	SETUMON_11	--
		,@WCJ_KAITO_11= 	KAITO_11	--
		,@WCJ_SETUMON_12= 	SETUMON_12	--
		,@WCJ_KAITO_12= 	KAITO_12	--
		,@WCJ_SETUMON_13= 	SETUMON_13	--
		,@WCJ_KAITO_13= 	KAITO_13	--
		,@WCJ_SETUMON_14= 	SETUMON_14	--
		,@WCJ_KAITO_14= 	KAITO_14	--
		,@WCJ_SETUMON_15= 	SETUMON_15	--
		,@WCJ_KAITO_15= 	KAITO_15	--
		,@WCJ_SETUMON_16= 	SETUMON_16	--
		,@WCJ_KAITO_16= 	KAITO_16	--
		,@WCJ_SETUMON_17= 	SETUMON_17	--
		,@WCJ_KAITO_17= 	KAITO_17	--
		,@WCJ_SETUMON_18= 	SETUMON_18	--
		,@WCJ_KAITO_18= 	KAITO_18	--
		,@WCJ_SETUMON_19= 	SETUMON_19	--
		,@WCJ_KAITO_19= 	KAITO_19	--
		,@WCJ_SETUMON_20= 	SETUMON_20	--
		,@WCJ_KAITO_20= 	KAITO_20	--
		,@WCJ_SETUMON_21= 	SETUMON_21	--
		,@WCJ_KAITO_21= 	KAITO_21	--
		,@WCJ_SETUMON_22= 	SETUMON_22	--
		,@WCJ_KAITO_22= 	KAITO_22	--
		,@WCJ_SETUMON_23= 	SETUMON_23	--
		,@WCJ_KAITO_23= 	KAITO_23	--
		,@WCJ_SETUMON_24= 	SETUMON_24	--
		,@WCJ_KAITO_24= 	KAITO_24	--
		,@WCJ_SETUMON_25= 	SETUMON_25	--
		,@WCJ_KAITO_25= 	KAITO_25	--
		,@WCJ_KONPON_YOIN_KB1=  	KONPON_YOIN_KB1	--
		,@WCJ_KONPON_YOIN_NAME1=  	KONPON_YOIN_NAME1	--
		,@WCJ_KONPON_YOIN_KB2=  	KONPON_YOIN_KB2	--
		,@WCJ_KONPON_YOIN_NAME2=  	KONPON_YOIN_NAME2	--
		,@WCJ_KONPON_YOIN_SYAIN_ID= 	KONPON_YOIN_SYAIN_ID	--
		,@WCJ_KONPON_YOIN_SYAIN_NAME= 	KONPON_YOIN_SYAIN_NAME	--
		,@WCJ_KISEKI_KOTEI_KB=  	KISEKI_KOTEI_KB	--
		,@WCJ_KISEKI_KOTEI_NAME=  	KISEKI_KOTEI_NAME	--
		,@WCJ_SYOCHI_A_SYAIN_ID=  	SYOCHI_A_SYAIN_ID	--
		,@WCJ_SYOCHI_A_SYAIN_NAME= 	SYOCHI_A_SYAIN_NAME	--
		,@WCJ_SYOCHI_A_YMDHNS=  	SYOCHI_A_YMDHNS	--
		,@WCJ_SYOCHI_B_SYAIN_ID=  	SYOCHI_B_SYAIN_ID	--
		,@WCJ_SYOCHI_B_SYAIN_NAME= 	SYOCHI_B_SYAIN_NAME	--
		,@WCJ_SYOCHI_B_YMDHNS=  	SYOCHI_B_YMDHNS	--
		,@WCJ_SYOCHI_C_SYAIN_ID=  	SYOCHI_C_SYAIN_ID	--
		,@WCJ_SYOCHI_C_SYAIN_NAME= 	SYOCHI_C_SYAIN_NAME	--
		,@WCJ_SYOCHI_C_YMDHNS=  	SYOCHI_C_YMDHNS	--
		,@WCJ_KYOIKU_FILE_PATH=  	KYOIKU_FILE_PATH	--
		,@WCJ_ZESEI_SYOCHI_YUKO_UMU= 	ZESEI_SYOCHI_YUKO_UMU	--
		,@WCJ_SYOSAI_FILE_PATH=  	SYOSAI_FILE_PATH	--
		,@WCJ_GOKI= 	GOKI	--
		,@WCJ_LOT= 	LOT	--
		,@WCJ_KENSA_TANTO_ID=  	KENSA_TANTO_ID	--
		,@WCJ_KENSA_TANTO_NAME=  	KENSA_TANTO_NAME	--
		,@WCJ_KENSA_TOROKU_YMDHNS= 	KENSA_TOROKU_YMDHNS	--
		,@WCJ_KENSA_GL_SYAIN_ID=  	KENSA_GL_SYAIN_ID	--
		,@WCJ_KENSA_GL_SYAIN_NAME= 	KENSA_GL_SYAIN_NAME	--
		,@WCJ_KENSA_GL_YMDHNS= 	KENSA_GL_YMDHNS	--
		,@WCJ_FILE_PATH1= 	FILE_PATH1	--
		,@WCJ_FILE_PATH2= 	FILE_PATH2	--
		,@WCJ_FUTEKIGO_HASSEI_YMD = FUTEKIGO_HASSEI_YMD
		FROM V009_CAR_R AS V009
		WHERE 
		HOKOKU_NO = @HOKOKUSYO_NO
		AND SASIMODOSI_YMDHNS = (SELECT MAX(WK.SASIMODOSI_YMDHNS) FROM V009_CAR_R WK WHERE WK.HOKOKU_NO = @HOKOKUSYO_NO AND WK.SASIMODOSI_YMDHNS < @SASIMODOSI_YMDHNS);

		SELECT 
		 @WCR_HOKOKU_NO= 	HOKOKU_NO	--
		,@WCR_BUMON_KB= 	BUMON_KB	--
		,@WCR_BUMON_NAME= 	BUMON_NAME	--
		,@WCR_CLOSE_FG= 	CLOSE_FG	--
		,@WCR_SETUMON_1= 	SETUMON_1	--
		,@WCR_KAITO_1= 	KAITO_1	--
		,@WCR_SETUMON_2= 	SETUMON_2	--
		,@WCR_KAITO_2= 	KAITO_2	--
		,@WCR_SETUMON_3= 	SETUMON_3	--
		,@WCR_KAITO_3= 	KAITO_3	--
		,@WCR_SETUMON_4= 	SETUMON_4	--
		,@WCR_KAITO_4= 	KAITO_4	--
		,@WCR_SETUMON_5= 	SETUMON_5	--
		,@WCR_KAITO_5= 	KAITO_5	--
		,@WCR_SETUMON_6= 	SETUMON_6	--
		,@WCR_KAITO_6= 	KAITO_6	--
		,@WCR_SETUMON_7= 	SETUMON_7	--
		,@WCR_KAITO_7= 	KAITO_7	--
		,@WCR_SETUMON_8= 	SETUMON_8	--
		,@WCR_KAITO_8= 	KAITO_8	--
		,@WCR_SETUMON_9= 	SETUMON_9	--
		,@WCR_KAITO_9= 	KAITO_9	--
		,@WCR_SETUMON_10= 	SETUMON_10	--
		,@WCR_KAITO_10= 	KAITO_10	--
		,@WCR_SETUMON_11= 	SETUMON_11	--
		,@WCR_KAITO_11= 	KAITO_11	--
		,@WCR_SETUMON_12= 	SETUMON_12	--
		,@WCR_KAITO_12= 	KAITO_12	--
		,@WCR_SETUMON_13= 	SETUMON_13	--
		,@WCR_KAITO_13= 	KAITO_13	--
		,@WCR_SETUMON_14= 	SETUMON_14	--
		,@WCR_KAITO_14= 	KAITO_14	--
		,@WCR_SETUMON_15= 	SETUMON_15	--
		,@WCR_KAITO_15= 	KAITO_15	--
		,@WCR_SETUMON_16= 	SETUMON_16	--
		,@WCR_KAITO_16= 	KAITO_16	--
		,@WCR_SETUMON_17= 	SETUMON_17	--
		,@WCR_KAITO_17= 	KAITO_17	--
		,@WCR_SETUMON_18= 	SETUMON_18	--
		,@WCR_KAITO_18= 	KAITO_18	--
		,@WCR_SETUMON_19= 	SETUMON_19	--
		,@WCR_KAITO_19= 	KAITO_19	--
		,@WCR_SETUMON_20= 	SETUMON_20	--
		,@WCR_KAITO_20= 	KAITO_20	--
		,@WCR_SETUMON_21= 	SETUMON_21	--
		,@WCR_KAITO_21= 	KAITO_21	--
		,@WCR_SETUMON_22= 	SETUMON_22	--
		,@WCR_KAITO_22= 	KAITO_22	--
		,@WCR_SETUMON_23= 	SETUMON_23	--
		,@WCR_KAITO_23= 	KAITO_23	--
		,@WCR_SETUMON_24= 	SETUMON_24	--
		,@WCR_KAITO_24= 	KAITO_24	--
		,@WCR_SETUMON_25= 	SETUMON_25	--
		,@WCR_KAITO_25= 	KAITO_25	--
		,@WCR_KONPON_YOIN_KB1=  	KONPON_YOIN_KB1	--
		,@WCR_KONPON_YOIN_NAME1=  	KONPON_YOIN_NAME1	--
		,@WCR_KONPON_YOIN_KB2=  	KONPON_YOIN_KB2	--
		,@WCR_KONPON_YOIN_NAME2=  	KONPON_YOIN_NAME2	--
		,@WCR_KONPON_YOIN_SYAIN_ID= 	KONPON_YOIN_SYAIN_ID	--
		,@WCR_KONPON_YOIN_SYAIN_NAME= 	KONPON_YOIN_SYAIN_NAME	--
		,@WCR_KISEKI_KOTEI_KB=  	KISEKI_KOTEI_KB	--
		,@WCR_KISEKI_KOTEI_NAME=  	KISEKI_KOTEI_NAME	--
		,@WCR_SYOCHI_A_SYAIN_ID=  	SYOCHI_A_SYAIN_ID	--
		,@WCR_SYOCHI_A_SYAIN_NAME= 	SYOCHI_A_SYAIN_NAME	--
		,@WCR_SYOCHI_A_YMDHNS=  	SYOCHI_A_YMDHNS	--
		,@WCR_SYOCHI_B_SYAIN_ID=  	SYOCHI_B_SYAIN_ID	--
		,@WCR_SYOCHI_B_SYAIN_NAME= 	SYOCHI_B_SYAIN_NAME	--
		,@WCR_SYOCHI_B_YMDHNS=  	SYOCHI_B_YMDHNS	--
		,@WCR_SYOCHI_C_SYAIN_ID=  	SYOCHI_C_SYAIN_ID	--
		,@WCR_SYOCHI_C_SYAIN_NAME= 	SYOCHI_C_SYAIN_NAME	--
		,@WCR_SYOCHI_C_YMDHNS=  	SYOCHI_C_YMDHNS	--
		,@WCR_KYOIKU_FILE_PATH=  	KYOIKU_FILE_PATH	--
		,@WCR_ZESEI_SYOCHI_YUKO_UMU= 	ZESEI_SYOCHI_YUKO_UMU	--
		,@WCR_SYOSAI_FILE_PATH=  	SYOSAI_FILE_PATH	--
		,@WCR_GOKI= 	GOKI	--
		,@WCR_LOT= 	LOT	--
		,@WCR_KENSA_TANTO_ID=  	KENSA_TANTO_ID	--
		,@WCR_KENSA_TANTO_NAME=  	KENSA_TANTO_NAME	--
		,@WCR_KENSA_TOROKU_YMDHNS= 	KENSA_TOROKU_YMDHNS	--
		,@WCR_KENSA_GL_SYAIN_ID=  	KENSA_GL_SYAIN_ID	--
		,@WCR_KENSA_GL_SYAIN_NAME= 	KENSA_GL_SYAIN_NAME	--
		,@WCR_KENSA_GL_YMDHNS= 	KENSA_GL_YMDHNS	--
		,@WCR_FILE_PATH1= 	FILE_PATH1	--
		,@WCR_FILE_PATH2= 	FILE_PATH2	--
		,@WCR_FUTEKIGO_HASSEI_YMD = FUTEKIGO_HASSEI_YMD
		FROM V009_CAR_R AS V009
		WHERE 
		HOKOKU_NO = @HOKOKUSYO_NO
		AND SASIMODOSI_YMDHNS = @SASIMODOSI_YMDHNS;

		--部門区分
		IF @WCJ_BUMON_KB	<>	@WCR_BUMON_KB
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			'製品区分'
			,@WCR_BUMON_NAME
			,@WCJ_BUMON_NAME
			);
		--設問内容1
		IF @WCJ_KAITO_1	<>	@WCR_KAITO_1 AND RTRIM(@WCJ_KAITO_1)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_1
			,@WCR_KAITO_1
			,@WCJ_KAITO_1
			);
		--設問内容2
		IF @WCJ_KAITO_2	<>	@WCR_KAITO_2 AND RTRIM(@WCJ_KAITO_2)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_2
			,@WCR_KAITO_2
			,@WCJ_KAITO_2
			);
		--設問内容3
		IF @WCJ_KAITO_3	<>	@WCR_KAITO_3 AND RTRIM(@WCJ_KAITO_3)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_3
			,@WCR_KAITO_3
			,@WCJ_KAITO_3
			);
		--設問内容4
		IF @WCJ_KAITO_4	<>	@WCR_KAITO_4 AND RTRIM(@WCJ_KAITO_4)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_4
			,@WCR_KAITO_4
			,@WCJ_KAITO_4
			);
		--設問内容5
		IF @WCJ_KAITO_5	<>	@WCR_KAITO_5 AND RTRIM(@WCJ_KAITO_5)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_5
			,@WCR_KAITO_5
			,@WCJ_KAITO_5
			);
		--設問内6
		IF @WCJ_KAITO_6	<>	@WCR_KAITO_6 AND RTRIM(@WCJ_KAITO_6)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_6
			,@WCR_KAITO_6
			,@WCJ_KAITO_6
			);
		--設問内7
		IF @WCJ_KAITO_7	<>	@WCR_KAITO_7 AND RTRIM(@WCJ_KAITO_7)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_7
			,@WCR_KAITO_7
			,@WCJ_KAITO_7
			);
		--設問内8
		IF @WCJ_KAITO_8	<>	@WCR_KAITO_8 AND RTRIM(@WCJ_KAITO_8)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_8
			,@WCR_KAITO_8
			,@WCJ_KAITO_8
			);
		--設問内9
		IF @WCJ_KAITO_9	<>	@WCR_KAITO_9 AND RTRIM(@WCJ_KAITO_9)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_9
			,@WCR_KAITO_9
			,@WCJ_KAITO_9
			);
		--設問内10
		IF @WCJ_KAITO_10	<>	@WCR_KAITO_10 AND RTRIM(@WCJ_KAITO_10)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_10
			,@WCR_KAITO_10
			,@WCJ_KAITO_10
			);
		--設問内11
		IF @WCJ_KAITO_11	<>	@WCR_KAITO_11 AND RTRIM(@WCJ_KAITO_11)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_11
			,@WCR_KAITO_11
			,@WCJ_KAITO_11
			);
		--設問内12
		IF @WCJ_KAITO_12	<>	@WCR_KAITO_12 AND RTRIM(@WCJ_KAITO_12)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_12
			,@WCR_KAITO_12
			,@WCJ_KAITO_12
			);
		--設問内13
		IF @WCJ_KAITO_13	<>	@WCR_KAITO_13 AND RTRIM(@WCJ_KAITO_13)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_13
			,@WCR_KAITO_13
			,@WCJ_KAITO_13
			);
		--設問内14
		IF @WCJ_KAITO_14	<>	@WCR_KAITO_14 AND RTRIM(@WCJ_KAITO_14)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_14
			,@WCR_KAITO_14
			,@WCJ_KAITO_14
			);
		--設問内15
		IF @WCJ_KAITO_15	<>	@WCR_KAITO_15 AND RTRIM(@WCJ_KAITO_15)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_15
			,@WCR_KAITO_15
			,@WCJ_KAITO_15
			);
		--設問内16
		IF @WCJ_KAITO_16	<>	@WCR_KAITO_16 AND RTRIM(@WCJ_KAITO_16)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_16
			,@WCR_KAITO_16
			,@WCJ_KAITO_16
			);
		--設問内17
		IF @WCJ_KAITO_17	<>	@WCR_KAITO_17 AND RTRIM(@WCJ_KAITO_17)<>'0'
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_17
			,@WCR_KAITO_17
			,@WCJ_KAITO_17
			);
		--設問内18
		IF @WCJ_KAITO_18	<>	@WCR_KAITO_18 AND RTRIM(@WCJ_KAITO_18)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_18
			,@WCR_KAITO_18
			,@WCJ_KAITO_18
			);
		--設問内19
		IF @WCJ_KAITO_19	<>	@WCR_KAITO_19 AND RTRIM(@WCJ_KAITO_19)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_19
			,@WCR_KAITO_19
			,@WCJ_KAITO_19
			);
		--設問内20
		IF @WCJ_KAITO_20	<>	@WCR_KAITO_20 AND RTRIM(@WCJ_KAITO_20)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_20
			,@WCR_KAITO_20
			,@WCJ_KAITO_20
			);
		--設問内21
		IF @WCJ_KAITO_21	<>	@WCR_KAITO_21 AND RTRIM(@WCJ_KAITO_21)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_21
			,@WCR_KAITO_21
			,@WCJ_KAITO_21
			);
		--設問内22
		IF @WCJ_KAITO_22	<>	@WCR_KAITO_22 AND RTRIM(@WCJ_KAITO_22)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_22
			,@WCR_KAITO_22
			,@WCJ_KAITO_22
			);
		--設問内23
		IF @WCJ_KAITO_23	<>	@WCR_KAITO_23 AND RTRIM(@WCJ_KAITO_23)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_23
			,@WCR_KAITO_23
			,@WCJ_KAITO_23
			);
		--設問内24
		IF @WCJ_KAITO_24	<>	@WCR_KAITO_24 AND RTRIM(@WCJ_KAITO_24)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_24
			,@WCR_KAITO_24
			,@WCJ_KAITO_24
			);
		--設問内25
		IF @WCJ_KAITO_25	<>	@WCR_KAITO_25 AND RTRIM(@WCJ_KAITO_25)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 @WCJ_SETUMON_25
			,@WCR_KAITO_25
			,@WCJ_KAITO_25
			);
		--根本要因区分1
		IF @WCJ_KONPON_YOIN_KB1	<>	@WCR_KONPON_YOIN_KB1 AND RTRIM(@WCJ_KONPON_YOIN_KB1)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '根本要因区分1'
			,@WCR_KONPON_YOIN_NAME1
			,@WCJ_KONPON_YOIN_NAME1
			);
		--根本要因区分2
		IF @WCJ_KONPON_YOIN_KB2	<>	@WCR_KONPON_YOIN_KB2 AND RTRIM(@WCJ_KONPON_YOIN_KB2)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '根本要因区分2'
			,@WCR_KONPON_YOIN_NAME2
			,@WCJ_KONPON_YOIN_NAME2
			);
		--根本要因社員ID
		IF @WCJ_KONPON_YOIN_SYAIN_ID	<>	@WCR_KONPON_YOIN_SYAIN_ID AND (@WCJ_KONPON_YOIN_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '根本要因社員'
			,@WCR_KONPON_YOIN_SYAIN_NAME
			,@WCJ_KONPON_YOIN_SYAIN_NAME
			);
		--帰責工程区分
		IF @WCJ_KISEKI_KOTEI_KB	<>	@WCR_KISEKI_KOTEI_KB AND RTRIM(@WCJ_KISEKI_KOTEI_KB)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '帰責工程区分'
			,@WCR_KISEKI_KOTEI_NAME
			,@WCJ_KISEKI_KOTEI_NAME
			);
		--処置実施A社員ID
		IF @WCJ_SYOCHI_A_SYAIN_ID	<>	@WCR_SYOCHI_A_SYAIN_ID AND (@WCJ_SYOCHI_A_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施A社員'
			,@WCR_SYOCHI_A_SYAIN_NAME
			,@WCJ_SYOCHI_A_SYAIN_NAME
			);
		--処置実施A日時
		IF @WCJ_SYOCHI_A_YMDHNS	<>	@WCR_SYOCHI_A_YMDHNS AND RTRIM(@WCJ_SYOCHI_A_YMDHNS)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施A日時'
			,@WCR_SYOCHI_A_YMDHNS
			,@WCJ_SYOCHI_A_YMDHNS
			);	
		--処置実施B社員ID
		IF @WCJ_SYOCHI_B_SYAIN_ID	<>	@WCR_SYOCHI_B_SYAIN_ID AND (@WCR_SYOCHI_B_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施B社員'
			,@WCR_SYOCHI_B_SYAIN_NAME
			,@WCJ_SYOCHI_B_SYAIN_NAME
			);
		--処置実施B日時
		IF @WCJ_SYOCHI_B_YMDHNS	<>	@WCR_SYOCHI_B_YMDHNS AND RTRIM(@WCJ_SYOCHI_B_YMDHNS)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施B日時'
			,@WCR_SYOCHI_B_YMDHNS
			,@WCJ_SYOCHI_B_YMDHNS
			);
		--処置実施C社員ID
		IF @WCJ_SYOCHI_C_SYAIN_ID	<>	@WCR_SYOCHI_C_SYAIN_ID AND (@WCJ_SYOCHI_C_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施C社員'
			,@WCR_SYOCHI_C_SYAIN_NAME
			,@WCJ_SYOCHI_C_SYAIN_NAME
			);
		--処置実施C日時
		IF @WCJ_SYOCHI_C_YMDHNS	<>	@WCR_SYOCHI_C_YMDHNS AND RTRIM(@WCJ_SYOCHI_C_YMDHNS)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '処置実施C日時'
			,@WCR_SYOCHI_C_YMDHNS
			,@WCJ_SYOCHI_C_YMDHNS
			);
		--教育記録ファイルパス
		IF @WCJ_KYOIKU_FILE_PATH <>	@WCR_KYOIKU_FILE_PATH AND RTRIM(@WCJ_KYOIKU_FILE_PATH)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '教育記録ファイル'
			,@WCR_KYOIKU_FILE_PATH
			,@WCJ_KYOIKU_FILE_PATH
			);
		--是正処置有効性有無
		IF @WCJ_ZESEI_SYOCHI_YUKO_UMU <>	@WCR_ZESEI_SYOCHI_YUKO_UMU AND RTRIM(@WCJ_ZESEI_SYOCHI_YUKO_UMU)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '教育記録ファイル'
			,@WCR_ZESEI_SYOCHI_YUKO_UMU
			,@WCJ_ZESEI_SYOCHI_YUKO_UMU
			);
		--詳細資料Noファイルパス
		IF @WCJ_SYOSAI_FILE_PATH <>	@WCR_SYOSAI_FILE_PATH AND RTRIM(@WCJ_SYOSAI_FILE_PATH)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '詳細資料Noファイル'
			,@WCR_SYOSAI_FILE_PATH
			,@WCJ_SYOSAI_FILE_PATH
			);
		--号機
		IF @WCJ_GOKI <>	@WCR_GOKI  AND RTRIM(@WCJ_GOKI)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '号機'
			,@WCR_GOKI
			,@WCJ_GOKI
			);
		--LOT
		IF @WCJ_LOT <>	@WCR_LOT AND (@WCJ_LOT)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 'LOT'
			,@WCR_LOT
			,@WCJ_LOT
			);
		--検査社員ID
		IF @WCJ_KENSA_TANTO_ID	<>	@WCR_KENSA_TANTO_ID AND (@WCJ_KENSA_TANTO_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '検査社員'
			,@WCR_KENSA_TANTO_NAME
			,@WCJ_KENSA_TANTO_NAME
			);
		--検査社員登録日時
		IF @WCJ_KENSA_TOROKU_YMDHNS	<>	@WCR_KENSA_TOROKU_YMDHNS AND RTRIM(@WCJ_KENSA_TOROKU_YMDHNS)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '検査社員登録日時'
			,@WCR_KENSA_TOROKU_YMDHNS
			,@WCJ_KENSA_TOROKU_YMDHNS
			);
		--検査GL社員ID
		IF @WCJ_KENSA_GL_SYAIN_ID	<>	@WCR_KENSA_GL_SYAIN_ID AND (@WCJ_KENSA_GL_SYAIN_ID)<>0
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '検査GL社員'
			,@WCR_KENSA_GL_SYAIN_NAME
			,@WCJ_KENSA_GL_SYAIN_NAME
			);
		--検査GL社員登録日時
		IF @WCJ_KENSA_GL_YMDHNS	<>	@WCR_KENSA_GL_YMDHNS AND RTRIM(@WCJ_KENSA_GL_YMDHNS)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '検査GL社員登録日時'
			,@WCR_KENSA_GL_YMDHNS
			,@WCJ_KENSA_GL_YMDHNS
			);
		--添付ファイル1
		IF @WCJ_FILE_PATH1	<>	@WCR_FILE_PATH1 AND RTRIM(@WCJ_FILE_PATH1)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '添付資料1'
			,@WCR_FILE_PATH1
			,@WCJ_FILE_PATH1
			);
		--添付ファイル2
		IF @WCJ_FILE_PATH2	<>	@WCR_FILE_PATH2 AND RTRIM(@WCJ_FILE_PATH2)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '添付資料2'
			,@WCR_FILE_PATH2
			,@WCJ_FILE_PATH2
			);
		--不適合発生日
		IF @WCJ_FUTEKIGO_HASSEI_YMD	<>	@WCR_FUTEKIGO_HASSEI_YMD AND RTRIM(@WCJ_FUTEKIGO_HASSEI_YMD)<>''
			INSERT INTO @retTBL (
			 KOMOKU_NAME	--項目名
			,MAE_NAIYO		--変更前内容
			,ATO_NAIYO		--変更後内容
			) VALUES (
			 '不適合発生日'
			,@WCR_FUTEKIGO_HASSEI_YMD
			,@WCJ_FUTEKIGO_HASSEI_YMD
			);			
	END

RETURN

END


