USE [FMS]
GO
/****** Object:  UserDefinedFunction [dbo].[TV03_SYOZOKU_SYAIN]    Script Date: 2018/11/15 11:09:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO






-- =============================================
-- Author:		JMS-
-- Create date: 2018.
-- Description:	所属社員情報取得
-- =============================================
ALTER FUNCTION [dbo].[TV03_SYOZOKU_SYAIN] 
(
	 @BUMON_KB				char(1)	--部門区分	 
) RETURNS
	@retTBL TABLE(
	 SYAIN_ID				int					--社員ID
	,SYAIN_NO				varchar(8)			--社員No
	,SIMEI					nvarchar(30)		--社員名
	,SIMEI_KANA				nvarchar(60)		--社員名カナ
	,BUMON_KB				char(1)
	,BUSYO_ID				int					--部署ID
	,BUSYO_NAME				nvarchar(30)		--部署名
	,GYOMU_GROUP_ID				int		--業務グループ
	,GYOMU_GROUP_NAME				nvarchar(30)		--業務グループ名
	,IS_LEADER			int --所属長かどうか(0:False 1:True
)
AS
BEGIN
	DECLARE	@W_SYAIN_ID						int;			--社員IDワーク
	DECLARE	@W_SYAIN_NO						int;			--社員No
	DECLARE @W_SIMEI						nvarchar(30);	--社員名
	DECLARE @W_SIMEI_KANA					nvarchar(60);	--社員名(カナ)
	DECLARE @W_BUMON_KB						char(1);
	DECLARE @W_BUSYO_ID						int;
	DECLARE @W_BUSYO_NAME					nvarchar(30);	
	DECLARE @W_GYOMU_GROUP_ID			int;
	DECLARE @W_GYOMU_GROUP_NAME		nvarchar(30);
	DECLARE @W_SYOZOKUCYO_ID			int;
	DECLARE @W_IS_LEADER			int;

	
	IF @BUMON_KB = 1 OR @BUMON_KB = 2
		--航空機部門
		DECLARE curTB CURSOR FOR
		SELECT M002.BUSYO_ID, M002.BUSYO_NAME, M002.BUMON_KB
		FROM M002_BUSYO M002
		WHERE M002.BUMON_KB IN (1, 2)
		AND M002.YUKO_YMD >= (SELECT MIN(YUKO_YMD) FROM M002_BUSYO WHERE BUMON_KB = M002.BUMON_KB AND YUKO_YMD >= FORMAT(GETDATE(), 'yyyyMMdd'))
		ORDER BY BUSYO_ID;
	ELSE
		--複合材その他
		DECLARE curTB CURSOR FOR
		SELECT BUSYO_ID, BUSYO_NAME, BUMON_KB
		FROM M002_BUSYO
		WHERE BUMON_KB = @BUMON_KB
		AND YUKO_YMD >= (SELECT MIN(YUKO_YMD) FROM M002_BUSYO WHERE BUMON_KB = @BUMON_KB AND YUKO_YMD >= FORMAT(GETDATE(), 'yyyyMMdd'))
		ORDER BY BUSYO_ID;
	
	OPEN curTB;
		
	WHILE 1 = 1
	BEGIN

		FETCH NEXT FROM curTB INTO 
		 @W_BUSYO_ID
		,@W_BUSYO_NAME
		,@W_BUMON_KB

		IF @@FETCH_STATUS <> 0
		BEGIN
			BREAK;
		END

		--所属部署マスタを検索
		DECLARE curTB2 CURSOR FOR
		SELECT
		SYAIN_ID,SYOZOKUCYO_ID
		FROM M005_SYOZOKU_BUSYO M005 INNER JOIN M002_BUSYO M002 ON (M005.BUSYO_ID = M002.BUSYO_ID)
		WHERE 
		    M005.BUSYO_ID = @W_BUSYO_ID
		AND M005.YUKO_YMD = (SELECT MIN(YUKO_YMD) FROM M005_SYOZOKU_BUSYO WHERE BUSYO_ID = @W_BUSYO_ID AND YUKO_YMD >=FORMAT(GETDATE(), 'yyyyMMdd'))

		
		OPEN curTB2;

		WHILE 1 = 1
		BEGIN
			
			SET @W_SYAIN_ID = null;

			FETCH NEXT FROM curTB2 INTO 
			 @W_SYAIN_ID,@W_SYOZOKUCYO_ID

			IF @@FETCH_STATUS <> 0
			BEGIN
				BREAK;
			END

			SELECT
				@W_SYAIN_NO = M004.SYAIN_NO
			  , @W_SIMEI = M004.SIMEI
			  , @W_SIMEI_KANA = M004.SIMEI_KANA
			  , @W_GYOMU_GROUP_ID = ISNULL(IIF(@W_BUSYO_ID=10,2, M011.GYOMU_GROUP_ID), 0)
			  , @W_GYOMU_GROUP_NAME = ISNULL((SELECT GYOMU_GROUP_NAME FROM M003_GYOMU_GROUP M003 WHERE M003.GYOMU_GROUP_ID = IIF(@W_BUSYO_ID=10,2,M011.GYOMU_GROUP_ID)) , '') 
			FROM
			  M005_SYOZOKU_BUSYO M005   
			  LEFT JOIN M004_SYAIN M004 
				ON M005.SYAIN_ID = M004.SYAIN_ID
			  LEFT JOIN M011_SYAIN_GYOMU M011 
				ON M011.SYAIN_ID = M004.SYAIN_ID			   
			WHERE
			  M004.SYAIN_ID = @W_SYAIN_ID AND M005.BUSYO_ID = @W_BUSYO_ID; 

			
			SET @W_IS_LEADER = IIF(@W_SYAIN_ID = @W_SYOZOKUCYO_ID,1,0)
			
			INSERT INTO @retTBL 
				(
				 SYAIN_ID				--社員ID
				,SYAIN_NO				--社員No
				,SIMEI					--社員名
				,SIMEI_KANA				--社員名カナ
				,BUMON_KB
				,BUSYO_ID				--部署ID
				,BUSYO_NAME				--部署名
				,GYOMU_GROUP_ID
				,GYOMU_GROUP_NAME
				,IS_LEADER
				) VALUES (
				 @W_SYAIN_ID			--社員ID
				,@W_SYAIN_NO			--社員No
				,@W_SIMEI				--社員名
				,@W_SIMEI_KANA			--社員名カナ
				,@W_BUMON_KB
				,@W_BUSYO_ID			--部署ID
				,@W_BUSYO_NAME			--部署名
				,@W_GYOMU_GROUP_ID
				,@W_GYOMU_GROUP_NAME
				,@W_IS_LEADER
				);
			
		END

		CLOSE curTB2;
		DEALLOCATE curTB2;
	END

	CLOSE curTB;
	DEALLOCATE curTB;

	RETURN;
	
RETURN

END


